### ISSUE TITLE
kubefwd cannot find root's kubeconfig

### ISSUE THREAD

**Issue by analbeard** [txn2/kubefwd#10]
I'm not sure whether this is more to do with my environment, but when I use Kubefwd it exits as it is looking for `/root/.kube/config` which obviously won't exist:

```bash
$ sudo kubefwd services --namespace shw
[sudo] password for shw: 

 _          _           __             _
| | ___   _| |__   ___ / _|_      ____| |
| |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
|   <| |_| | |_) |  __/  _|\ V  V / (_| |
|_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|

Press [Ctrl-C] to stop forwarding.
Loading hosts file /etc/hosts
Backing up your original hosts file /etc/hosts to /etc/hosts.original
panic: stat /root/.kube/config: no such file or directory

goroutine 1 [running]:
github.com/txn2/kubefwd/pkg/utils.K8sConfig(0x1bc4f60, 0x0)
	/Users/cjimti/go/src/github.com/txn2/kubefwd/pkg/utils/utils.go:83 +0x19b
github.com/txn2/kubefwd/cmd/kubefwd/services.glob..func1(0x1bc4f60, 0xc0002e8720, 0x0, 0x2)
	/Users/cjimti/go/src/github.com/txn2/kubefwd/cmd/kubefwd/services/services.go:78 +0x138
github.com/txn2/kubefwd/vendor/github.com/spf13/cobra.(*Command).execute(0x1bc4f60, 0xc0002e8700, 0x2, 0x2, 0x1bc4f60, 0xc0002e8700)
	/Users/cjimti/go/src/github.com/txn2/kubefwd/vendor/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/txn2/kubefwd/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0002ecc80, 0xc0002ecc80, 0xc0002ecf00, 0x1bc4f60)
	/Users/cjimti/go/src/github.com/txn2/kubefwd/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/txn2/kubefwd/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0002ecc80, 0x1, 0x1)
	/Users/cjimti/go/src/github.com/txn2/kubefwd/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/Users/cjimti/go/src/github.com/txn2/kubefwd/cmd/kubefwd/kubefwd.go:64 +0x67
```

If I need to make changes to my sudoers config then that's not a problem.

**Comment by analbeard** [comment]
Not to worry, I actually missed the help page for the `services` command. I can see that it picks up the correct path to my kubeconfig there, but obviously this doesn't persist when using sudo.

I don't currently export the path to my kubeconfig as an env var - doing that makes things work correctly:

```bash
$ echo $KUBECONFIG 
/home/shw/.kube/config
$ sudo !!
sudo echo $KUBECONFIG 
/home/shw/.kube/config
```

I can always do this to work around the issue - thanks!

**Comment by colmm99** [comment]
I've used sudo with the -E option so it takes my users ~/.kube/config, this works fine.

e.g. 
sudo -E kubefwd services -n $NAMESPACE

The other option is to copy your ~/.kube/config to the root users .kube/config

**Comment by analbeard** [comment]
@colmm99 that works nicely, I could edit my sudoers config to preserve the $KUBECONFIG env var but this is less messy. Thanks!

@cjimti please feel free to close this if you no longer need it.

**Comment by cjimti** [comment]
1.4.9 should correctly pick up on the KUBECONFIG environment variable, allowing `sudo -E` to be used when you have KUBECONFIG pointing to a preferred config.  The KUBECONFIG env can still be overridden with `-s /path/to/config`.
