### ISSUE TITLE
Kubefwd should print forwarding paths as URLS

### ISSUE THREAD

**Issue by daxmc99** [txn2/kubefwd#104]
Today, kubefwd prints 
```
INFO[09:52:34] Forwarding: linkerd-sp-validator:443 to pod linkerd-sp-validator-7d55ff4b77-llpp7:8443
INFO[09:52:35] Forwarding: linkerd-web:8084 to pod linkerd-web-7f9f9ccc45-gw7fv:8084
INFO[09:52:35] Forwarding: linkerd-web:9994 to pod linkerd-web-7f9f9ccc45-gw7fv:9994
INFO[09:52:35] Forwarding: linkerd-controller-api:8085 to pod linkerd-controller-585d9d4c8-gp9fr:8085
INFO[09:52:36] Forwarding: linkerd-prometheus:9090 to pod linkerd-prometheus-59fb5b4575-w4scj:9090
INFO[09:52:37] Forwarding: linkerd-tap:8088 to pod linkerd-tap-6948875d5d-pcgj6:8088
```

If kubefwd instead printed something like

INFO[09:52:36] Forwarding: **http://** linkerd-prometheus:9090 to pod linkerd-prometheus-59fb5b4575-w4scj:9090 

then the link would be clickable from my terminal (iterm2).

**Comment by cjimti** [comment]
@daxmc99 sounds like a nice addition, however many people like myself forward many non-HTTP-based services, so displaying things like http://mysql:3306, http://hive:10000, http://tcp-echo:5500 would be wrong. I think it would be a significate effort and unreliable to determine the protocol.

**Comment by cjimti** [comment]
@daxmc99 just a thought, you might try something like this:

`sudo kubefwd svc -n demo |sed 's/ing: /ing: http:\/\//'` 

I am sure with some experimentation you could streamline it.

**Comment by daxmc99** [comment]
Thanks! This works
