### ISSUE TITLE
When multiple namespaces are forwarded, only the first provided namespace appends namespace to the hostname.

### ISSUE THREAD

**Issue by zcmack** [txn2/kubefwd#108]
I tried to make sense of https://github.com/txn2/kubefwd/issues/4 that lead to ability to provide multiple namespaces to forward, but I'm still a bit uncertain about this behavior. 

`	
// ShortName field only use short name for the first namespace and context
`
...`
		if opts.ShortName != true {
				serviceHostName = serviceHostName + "." + pod.Namespace
			}`

This has lead to some inconsistencies within my team, depending on which order the namespaces are flagged for forwarding, one user will commit a development configuration referencing `redis.db` and `microservice-1` where another user will expect `redis` and `microservice-1.appname`.

I propose that this is configurable behavior, as it seems to be by design according to the original issue referenced above.

It seems like a straightforward change, but I would like opinions on the best way to implement. A single flag at the CLI, such as `--hostnames` `--fq` for a more terse "fully-qualified"?

**Comment by cjimti** [comment]
@zcmack every entry gets `SERVICE.NAMESPACE` and `SERVICE.NAMESPACE.svc.cluster.local`, however, the first forwarded namespace also gets a non-namespaced entry. The logged output does not show all the rules added to the /etc/hosts.

While running `kubefwd` check out `/etc/hosts` and you should see the entries. 

Example for `kubefwd svc -n first -n second` assuming the namespaces first and second have services a, b and c.

```
127.1.28.1       a a.first.svc.cluster.local a.first
127.1.28.2       b b.first.svc.cluster.local b.first
127.1.28.3       c c.first.svc.cluster.local c.first
127.1.28.4       a.second.svc.cluster.local a.second
127.1.28.5       b.second.svc.cluster.local b.second
127.1.28.6       c.second.svc.cluster.local c.second
```

**Comment by cjimti** [comment]
@zcmack keep in mind the non-namespaced service (the first one forwarded) is only a convenience for developing as though you are in that namespace, however, all services may be accessed by service.namespace or service.namespace.svc.cluster.local.
