### ISSUE TITLE
kubefwd with microk8s: 127.0.0.1:8080: connect: connection refused 

### ISSUE THREAD

**Issue by IliaRusin** [txn2/kubefwd#112]
Hi!

I've started using kubefwd with microk8s. 

On the first run of ` sudo kubefwd svc -n local` I've got an error:

```
ERRO[14:10:58] Runtime error: pkg/mod/k8s.io/client-go@v0.0.0-20191108070106-f8f007fd456c
/tools/cache/reflector.go:108: Failed to list *v1.Service:
 Get "http://localhost:8080/api/v1/namespaces
/local/services?limit=500&resourceVersion=0":
 dial tcp 127.0.0.1:8080: connect: connection refused 
```

Command `kubectl port-forward deployment/postgres 5432:5432` works well:

```
Forwarding from 127.0.0.1:5432 -> 5432
Forwarding from [::1]:5432 -> 5432
Handling connection for 5432
```

There is an alias in `~/.bash_aliases` also:
```
kubectl='microk8s.kubectl'
```

My previous experience with `kubefwd` and `minikube` was quite nice.

**Comment by cjimti** [comment]
I don't use microk8s so I am not certain where it stores the connection configuration. Kubefwd does not use kubectl, only the configuration files. 

You can specify them directly with `-c, --kubeconfig string   absolute path to a kubectl config file`.

**Comment by IliaRusin** [comment]
Thank you!

I've missed this line in `microk8s` [README.md
](https://github.com/ubuntu/microk8s/blob/b2b55883ac1636eca8d0c07c84bbec9452ed1b68/README.md).

Just need to write to `~/.kube/config`:
```
sudo microk8s.kubectl config view --raw > $HOME/.kube/config
```
