### ISSUE TITLE
 ERROR: unable to listen on any of the requested ports: [{3306 3306}]

### ISSUE THREAD

**Issue by shivamnc** [txn2/kubefwd#115]
maria db port not aceessing.

 Forwarding: gateway-mysql:3306 to pod gateway-mysql-6c7bb4bf4c-w9bnn:3306
 ERROR: unable to listen on any of the requested ports: [{3306 3306}]

Actually this port not required to access remote side, but kubfwd is stopping here. Not accessing

**Comment by cjimti** [comment]
Does `kubectl port-forward` work for your service?

**Comment by shivamnc** [comment]
Not working  i reinstalled  again and using kind cluster following error came

INFO[20:40:20]  _          _           __             _
INFO[20:40:20] | | ___   _| |__   ___ / _|_      ____| |
INFO[20:40:20] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
INFO[20:40:20] |   <| |_| | |_) |  __/  _|\ V  V / (_| |
INFO[20:40:20] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
INFO[20:40:20]
INFO[20:40:20] Version 1.13.0
INFO[20:40:20] https://github.com/txn2/kubefwd
INFO[20:40:20]
INFO[20:40:20] Press [Ctrl-C] to stop forwarding.
INFO[20:40:20] 'cat /etc/hosts' to see all host entries.
INFO[20:40:20] Loaded hosts file /etc/hosts
INFO[20:40:20] Hostfile management: Original hosts backup already exists at /root/hosts.original
INFO[20:40:20] Forwarding: ahyushhra:8081 to pod ahyushhra-684c7fd97c-zqckj:8081
INFO[20:40:20] Forwarding: ahyushhra-elasticsearch:9200 to pod ahyushhra-elasticsearch-7d78fbccf-djqtr:9200
INFO[20:40:20] Forwarding: ahyushhra-elasticsearch:9300 to pod ahyushhra-elasticsearch-7d78fbccf-djqtr:9300
INFO[20:40:20] Forwarding: gateway:8080 to pod gateway-848ff8f467-z9l4v:8080
INFO[20:40:21] Forwarding: gateway-elasticsearch:9200 to pod gateway-elasticsearch-67db675bc9-w576t:9200
INFO[20:40:21] Forwarding: gateway-elasticsearch:9300 to pod gateway-elasticsearch-67db675bc9-w576t:9300
INFO[20:40:22] Forwarding: jhipster-grafana:3000 to pod jhipster-grafana-66c5c55bbf-8v4f7:3000
panic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod

goroutine 181 [running]:
github.com/txn2/kubefwd/pkg/fwdport.(*PortForwardOpts).WaitForPodRunning(0xc000020690, 0xc000089200, 0x0, 0x0, 0x0)
        /Users/cjimti/workspace/txn2/kubefwd/pkg/fwdport/fwdport.go:306 +0x617
github.com/txn2/kubefwd/pkg/fwdport.(*PortForwardOpts).PortForward(0xc000020690, 0x0, 0x0)
        /Users/cjimti/workspace/txn2/kubefwd/pkg/fwdport/fwdport.go:130 +0x7ca
github.com/txn2/kubefwd/cmd/kubefwd/services.(*FwdServiceOpts).LoopPodToForward.func1(0xc000020690, 0xc000020870)
        /Users/cjimti/workspace/txn2/kubefwd/cmd/kubefwd/services/services.go:474 +0x32
created by github.com/txn2/kubefwd/cmd/kubefwd/services.(*FwdServiceOpts).LoopPodToForward
        /Users/cjimti/workspace/txn2/kubefwd/cmd/kubefwd/services/services.go:473 +0x91c
[root@mainnode ~]# panic: interface conversion: runtime.Object is *v1.Status, not *v1.Podpanic: interface conversion: runtime.Object is *v1.Status, not *v1.Podpanic: interface conversion: runtime.Object is *v1.Status, not *v1.Pod
-bash: panic:: command not found

**Comment by cjimti** [comment]
These are two separate issues. 

First Issue: Are you able to `kubectl port-forward` your gateway-mysql?
The second Issue is #114
