### ISSUE TITLE
Only a single pod bound per service?

### ISSUE THREAD

**Issue by vemv** [txn2/kubefwd#12]
Hi,

let's say I install Kafka like the following:

`helm install --name wd-kafka --namespace kafka -f "kafka-helm.yml" incubator/kafka`

...kafka-helm.yml having the following content: `replicas: 3`.

Then, accordingly, I'll get a service with 3 pods:

![image](https://user-images.githubusercontent.com/1162994/48076285-2c317800-e1e5-11e8-8b57-dde324fe149e.png)

But now when I run `sudo kubefwd services -n default -n kafka` I wil get only the following:

```
Fwd 127.1.28.1:9092 as wd-kafka.kafka.svc.cluster.local:9092 to pod wd-kafka-0:kafka
```

This seems fishy - it seems as if the other two pods were ignored.

I think all this has to do with the low reliability Kafka-over-Kubefwd is having for me.

Can't the following happen...?

* pod 1 goes down, but the other two are operational
* kubefwd still points to the faulty pod.

We briefly talked about reconnects, over email. But if I'm not mistaken the issue is broader than that (although re-connects might reduce the pain): port forwarding operates at pod level, rather than at service level.

WDYT?

Thanks - Victor

**Comment by cjimti** [comment]
@vemv it forwards to a single pod for a couple of reasons:

1. kubefwd is essentially `kubectl port-forward` under the hood. It uses the same API calls but allows binding to local IPs other than 127.0.0.1, and does them in bulk along with a name.
2. when our team is developing we often want to see the logs on the pods we are communicating with, so if some services http://some-api:3131 is giving errors and has dozens of pods it makes that really difficult. 
3. this sounds like a great optional feature, maybe specified with a flag? However I need to research the k8s API to see if port-forwarding to a service is even possible. At the moment I use the service to find the pods and forward to the first one, then report that back to the user so you know which one you are working with. 

Thank you, it is helpful for me to understand other use cases like this and hope kubefwd continues to solve development problems for other teams as well.

**Comment by vemv** [comment]
Thanks for the reply! Understood.

As I kept researching the underlying issue, I realised that "services vs. pods" wasn't really the problem. 

So this feature isn't particularly desired for me anymore (although it does sound like a good idea... but optional, as you say)

**Comment by cjimti** [comment]
I added a todo for re-connect after a failure. I'll research service forwarding, but lower the priority on it.
