### ISSUE TITLE
port forwarding breaks when connecting to a Zookeeper node

### ISSUE THREAD

**Issue by karannparikh** [txn2/kubefwd#120]
Runtime error: an error occurred forwarding 2888 -> 2888: error forwarding port 2888 to pod xxxxx, uid: exit status 1: socat[29346] E connect(5, AF=2 127.0.0.1:2888, 16): Connection refused

**Comment by cjimti** [comment]
Are you able to use `kubectl port-forward'?

**Comment by karannparikh** [comment]
@cjimti Thanks for looking into it. Appreciate your help :-) The problem does not lie with kubefwd. There was an issue with the way the service was setup.
