### ISSUE TITLE
MacOS container not able access the kubefwd port forwarding

### ISSUE THREAD

**Issue by karannparikh** [txn2/kubefwd#129]
Hey,
 I am running kubefwd on my host machine. I am able to access the Zookeeper cluster on my host machine:
```
telnet zk-0.svc.cluster.local 2181
Trying 127.1.27.15...
Connected to zk-0.
Escape character is '^]'.
```

But when I run the same command within a centOS7 container, I am unsuccessful:
```
telnet  zk-0.svc.cluster.local 2181
Trying 127.1.27.15...
telnet: connect to address 127.1.27.15: Connection refused
```

What I find interesting is that, the container is able to resolve the hostname using the hosts "/etc/hosts", but not able to connect to the Zookeeper cluster.

**Comment by cjimti** [comment]
you would need to run `kubefwd` inside the centOS7 container. The `kubefwd` forwards to loopback interfaces on the (host) machine running `kubefwd`. Your centOS7 container does not know how to get to the 127.1.27.15 address on your host machine.
