### ISSUE TITLE
Using forwarded hostnames from inside a container

### ISSUE THREAD

**Issue by yoni-taranis** [txn2/kubefwd#135]
I am not sure if this is a kubefwd issue,

I am successfuly forwarding the hosts from the cluster when running kubefwd, also, I can resolve each host to the right IP from a locally running docker container.

But when trying to access that same host using http, I receive connection refused.

Is this an issue in kubefwd? (I don't think so) 
Is it an issue with the forwarding feature of k8s?

I have tried this with Docker for Windows (vbox) and Docker Desktop

**Comment by yoni-taranis** [comment]
I guess the issue is because of the host being resolved to 127.1 on the docker container, but when trying to access that host using http, it's not really accessing the host machine

Am I correct?
Is the only way to do it on docker is by running kubefwd locally on the docker machine?

**Comment by cjimti** [comment]
`kubefwd` adds local network interfaces and modified /etc/hosts. If you execute `kubefwd` inside a container the /etc/host and network interfaces exist inside the container. If you want to `kubefwd` forward on the host machine you need to mount /etc/hosts and use host networking. 

Most people do not run `kubefwd` from within a container unless they specifically want to forward into that container.
