### ISSUE TITLE
":8080 connect: connection refused"

### ISSUE THREAD

**Issue by cflewis** [txn2/kubefwd#137]
kubefwd can't connect to my cluster at all, which I do not understand :(

```
❯ sudo -E /usr/local/bin/kubefwd svc -n foo
INFO[17:35:25]  _          _           __             _     
INFO[17:35:25] | | ___   _| |__   ___ / _|_      ____| |    
INFO[17:35:25] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |    
INFO[17:35:25] |   <| |_| | |_) |  __/  _|\ V  V / (_| |    
INFO[17:35:25] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|    
INFO[17:35:25]                                              
INFO[17:35:25] Version 1.14.0                               
INFO[17:35:25] https://github.com/txn2/kubefwd              
INFO[17:35:25]                                              
INFO[17:35:25] Press [Ctrl-C] to stop forwarding.           
INFO[17:35:25] 'cat /etc/hosts' to see all host entries.    
INFO[17:35:25] Loaded hosts file /etc/hosts                 
INFO[17:35:25] Hostfile management: Original hosts backup already exists at /root/hosts.original 
FATA[17:35:25] Error connecting to k8s cluster: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused 
```

The kubecontext is set correctly:

```
kubectl cluster-info
Kubernetes master is running at ...
<SNIP>
```

Is there something obvious I am doing wrong?

The cluster is running on GKE.

Thanks in advance :smiley:

**Comment by mastern2k3** [comment]
same happening for me, recently upgraded mint from 19.3 to 20.

**Comment by cjimti** [comment]
It is trying to connect to `localhost:8080` is that the server address of your Kubernetes master (API server) for the current context?  I am assuming it's loading the wrong context. Can you try specifying the config file directly?

`sudo kubefwd svc -n foo -c ~/.kube/config`

**Comment by cflewis** [comment]
Can confirm this works. Perhaps it is trying to read a kubeconfig from the superuser?

**Comment by cjimti** [comment]
yes, a clue is that it tries to store a backup /etc/hosts in the home directory of the user. In your case it used `/root/hosts.original` and means it thinks your home directory is /root/. 

`sudo` on `kubectl` would probably yield the same result.

**Comment by cjimti** [comment]
FYI: `kubefwd` can also use the value of the environment var KUBECONFIG. So you can also `export KUBECONFIG=/home/someuser/.kube/config` etc...

**Comment by edouard-lopez** [comment]
Also works with `-E` or `--preserve-env`  for me:

    sudo --preserve-env kubefwd svc -n foo
