### ISSUE TITLE
FieldSelector: "status.phase=Running" code take out in 1.10.0 Reason?

### ISSUE THREAD

**Issue by rshelby5** [txn2/kubefwd#139]
Code for the field selector was taken out in 1.10.0? Any specific reason it was taken out in 1.10.0?

https://github.com/txn2/kubefwd/commit/6a863539c7b114510fd1092950927ce5c2c44d84

**Comment by cjimti** [comment]
@rshelby5 have you tried the latest version? What issues are you having?
