### ISSUE TITLE
Stops forwarding some services if they are temporarily unavailable, never forwards again

### ISSUE THREAD

**Issue by dobesv** [txn2/kubefwd#141]
It seems like I have to restart kubefwd periodically because it will sometimes stop forwarding a service and then it never tries to forward it again.  It would be nice if it would automatically detect that a service is back online and forward to it again.

**Comment by dobesv** [comment]
I wonder if this logic might be the issue:

```
	if !force && time.Since(svcfwd.LastSyncedAt) < 10*time.Minute {
		log.Debugf("Skipping pods refresh for %s due to rate limiting", svcfwd)
		return
	}
```

10 minutes seems like a long time to wait between applying changes, I wonder 10 seconds would be enough of a throttling time?

Also, I wonder if it would be better if this was a "debounce" type algorithm.  The way this works is it will process the *first* change within the 10 minute span, then wait 10 minutes.  What might be better is if a change comes in, it starts a timer and waits until no new changes have arrived within a few seconds, then it updates the list of pods.

**Comment by cjimti** [comment]
I have removed a lot of the automatic re-syncing which stabilized it for me.  I can leave now 1.17.2 connected most of the day without interruption. Maybe we can revisit connection checking in the future.

**Comment by dobesv** [comment]
I am still having this issue running from the master branch.  It doesn't affect all the services but I do have some services that I almost always have to restart kubefwd to access because it has disconnected and not tried to connect again.
