### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by flupec** [txn2/kubefwd#143]
Hi, after starting kubefwd i cannot send a request to any service - it is rejected by a timeout.

kubefwd output seems fine, the names of the services and their ports correspond to expectations.

Even kubectl port-forward works fine.
```
λ kubectl port-forward service/microservice 8080:8080
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
```

When kubefwd is running i can ping microservice
```
λ ping microservice

Pinging microservice [127.1.27.4] with 32 bytes of data:
Reply from 127.1.27.4: bytes=32 time<1ms TTL=128
Reply from 127.1.27.4: bytes=32 time<1ms TTL=128
Reply from 127.1.27.4: bytes=32 time<1ms TTL=128
Reply from 127.1.27.4: bytes=32 time<1ms TTL=128

Ping statistics for 127.1.27.4:
Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
Minimum = 0ms, Maximum = 0ms, Average = 0ms
```

Also, the host file appears to be valid. Do you know what this may be due to?

**Comment by dobesv** [comment]
FWIW you will always be able to ping those kubefwd IP addresses because they are your own computer.

I'm not the maintainer but I'd suggest at least providing the full command line you are using to run kubefwd and its full output.

**Comment by flupec** [comment]
Sorry, found that this was a firewall issue.
