### ISSUE TITLE
Caused by: java.net.BindException: Address already in use

### ISSUE THREAD

**Issue by xbeta** [txn2/kubefwd#147]
I have a microservice development environment.  I have 3 services: A, B, C

A is the one I am currently doing local development, and will run Java Spring Boot as `gradle bootRun` to run it locally.
A needs services B, C to function.

How do I use `kubefwd` to only forward B and C, but not A, so I won't get the following error when running `bootRun` on service A locally.

```
Caused by: java.net.BindException: Address already in use
```

**Comment by cjimti** [comment]
You can use selectors to choose what services you wish to bind to.

However, you can avoid the error you see if your local service listens on 127.0.0.1 and not 0.0.0.0 (all interfaces). kubefwd sets up separate internal interfaces 127.1.x.x so it can forward multiple services using the same port.

**Comment by xbeta** [comment]
@cjimti Can `kubefwd` forwards to `localhost` or `127.0.0.1` by defaults? 

in my chase, it forwards to hostname `curl B:10007/api/foobar`

**Comment by cjimti** [comment]
`kubefwd` uses many 127 addresses and leaves 127.0.0.1 (localhost) for you to bind your local services to. I don't know Java Spring Boot but you should look into how to start you service on a specif IP like 127.0.0.1. 0.0.0.0 is probably the default.

**Comment by xbeta** [comment]
@cjimti quick question for you

Does `kubefwd` has something for `.kubefwdconfig` that stores in global and local path? We can set it in a config file which lets us use selector to choose what it can be exclude/include for the address to forward.

**Comment by cjimti** [comment]
Check out the `kubectl` examples using selectors. Kubefwd uses the same `-l` argument https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering

**Comment by xbeta** [comment]
> Check out the `kubectl` examples using selectors. Kubefwd uses the same `-l` argument https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering

Got it, thanks. 

Do `kubefwd` team plans to implement something like `.kubefwdconfig` in the future?

**Comment by cjimti** [comment]
Sounds like you could just create command aliases such as: 
`alias fwdx=sudo kubefwd svc -n project_ns -l "app in (B, C)"`

**Comment by xbeta** [comment]
> Sounds like you could just create command aliases such as:
> `alias fwdx=sudo kubefwd svc -n project_ns -l "app in (B, C)"`

The reason I asked is, we can check in the per project `.kubeconfig` file, and share with our teams too.  

Just a thought.

**Comment by cjimti** [comment]
Thanks for the suggestion, if I understand the request right I think it's out of scope for `kubefwd`. Higher-level tooling would do a better job, like shell scripts make, etc..
