### ISSUE TITLE
unable to do port forwarding: socat not found.

### ISSUE THREAD

**Issue by prettyyjnic** [txn2/kubefwd#15]
vagrant@ubuntu:~$ sudo /usr/local/bin/kubefwd services

 _          _           __             _
| | ___   _| |__   ___ / _|_      ____| |
| |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
|   <| |_| | |_) |  __/  _|\ V  V / (_| |
|_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|

Press [Ctrl-C] to stop forwarding.
Loading hosts file /etc/hosts
Original hosts backup already exists at /etc/hosts.original
Fwd 127.1.27.1:8080 as hello-minikube:8080 to pod hello-minikube-6c47c66d8-pnh66:8080
Fwd 127.1.27.2:443 as kubernetes:443 to pod hello-minikube-6c47c66d8-pnh66:8443
E1109 09:48:49.372871   10016 portforward.go:352] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 1db44e20e4a1a128fa733e2f5bbc1656cdb3194fbeb4436f678aed52f70f0b3a, uid : unable to do port forwarding: socat not found.
E1109 09:48:57.673534   10016 portforward.go:352] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 1db44e20e4a1a128fa733e2f5bbc1656cdb3194fbeb4436f678aed52f70f0b3a, uid : unable to do port forwarding: socat not found.
E1109 09:48:59.132190   10016 portforward.go:352] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 1db44e20e4a1a128fa733e2f5bbc1656cdb3194fbeb4436f678aed52f70f0b3a, uid : unable to do port forwarding: socat not found.

**Comment by mgoldbas** [comment]
What was the appropriate solution to this issue?

**Comment by cjimti** [comment]
Are you able to do `kubectl port-forward`? It looks at though socat is not installed on the nodes.

**Comment by hnicke** [comment]
Your kubernetes version might be too old. Had the same problem. Kubernetes added `socat` somewhere around v1.10 or v1.11. Either upgrade the kubernetes version (if possible) or manually install `socat` on each node.
