### ISSUE TITLE
kubefwd usage as a module

### ISSUE THREAD

**Issue by flupec** [txn2/kubefwd#158]
Hello.

How i can use the newest version of your project as a go module?

```
flupec@dell:~/Idea-projects/test$ go get github.com/txn2/kubefwd@v1.9.4
go: finding github.com/txn2/kubefwd v1.9.4
go: finding github.com v1.9.4
go: finding github.com/txn2 v1.9.4
go: downloading github.com/txn2/kubefwd v1.9.4
go: extracting github.com/txn2/kubefwd v1.9.4
flupec@dell:~/Idea-projects/test$ go get github.com/txn2/kubefwd@v1.17.3
go: finding github.com/txn2/kubefwd v1.17.3
go: finding github.com/txn2/kubefwd v1.17.3
go get github.com/txn2/kubefwd@v1.17.3: github.com/txn2/kubefwd@v1.17.3: invalid version: unknown revision v1.17.3
flupec@dell:~/Idea-projects/test$
```

Can you explain why i cannot use 1.17.3 version ? (and other versions that greater than 1.13.1)

**Comment by cjimti** [comment]
drop the v. `go get github.com/txn2/kubefwd@1.17.3`
It's now really intended to be used a a module so YMMV on how suitable it is for your project.

**Comment by cjimti** [comment]
I see there is another issue, it looks like go proxy points to an older version. I re-opened the ticket and will try to investigate soon.

**Comment by cjimti** [comment]
I have no clue how to fix this. 

`go get github.com/txn2/kubefwd@1.18.0`

returns: `go: github.com/txn2/kubefwd 1.18.1 => v1.17.5-0.20210315215958-f5db6f4afd06`

f5db6f4afd06 is the correct commit for 1.18.1, I don't know why it's showing  v1.17.5.

**Comment by flupec** [comment]
It's necessary to make releases with a "v" prefix in tag.
Valid: https://github.com/txn2/kubefwd/tree/v1.17.4 (with "v")
Not valid: https://github.com/txn2/kubefwd/tree/1.18.0 (without "v")

**Comment by flupec** [comment]
Can you please try to make a new release with such prefix? There's a change that goproxy will be able to resolve new version.

**Comment by cjimti** [comment]
@flupec I added a v1.20.0 tag. I plan to release a new version once my issue with https://github.com/txn2/kubefwd/pull/189 is resolved. Would you be able to look at that first? Thanks
