### ISSUE TITLE
Support shorthand service names

### ISSUE THREAD

**Issue by jakereps** [txn2/kubefwd#16]
One thing I ran into with some of my app configuration was that on kubedns you are able to shorthand a service name, but kubefwd doesn't appear to add that variant to the hosts file at the moment. To expand, I mean instead of `service.namespace.svc.cluster.local` you can put `service.namespace` and it will resolve. Could this be included in the aliases added to the hosts file? I haven't dug into the code yet, but I'd volunteer to add the functionality if need be 👍.

**Comment by cjimti** [comment]
This was certainly an oversight and very easy to fix. I’m traveling at the moment but could add it in on Monday or I can assign it to you if you are interested.

Thank you for the report.

**Comment by cjimti** [comment]
@jakereps 1.4.3 should now support service.namespace for all forwarded namespaces. see: https://github.com/txn2/kubefwd/releases/tag/1.4.3

`brew upgrade kubefwd` if you are running homebrew

**Comment by jakereps** [comment]
Awesome, thanks a ton! 👍 Crazy turnaround on that! Offline for a few days so didn't even get a chance to respond!

**Comment by cjimti** [comment]
@jakereps thank you for reporting the issue. I've been getting a lot of positive feedback on kubefwd and hope it helps others. Simple requests like this I'll try to turn around quickly.
