### ISSUE TITLE
Disconnects every 5 minutes using mobile internet

### ISSUE THREAD

**Issue by mnvx** [txn2/kubefwd#163]
I run kubefwd from my office to connect to another office through VPN and mobile internet. It works well about first 5 minutes but after that I have in log

```
ERRO[18:19:15] Runtime: error creating error stream for port 5432 -> 5432: Timeout occured 
ERRO[18:20:26] Runtime: error creating error stream for port 5432 -> 5432: Timeout occured 
```

How it is possible to avoid it, may be kubefwd have any option for automatic reconnects on fails?

**Comment by cjimti** [comment]
@mnvx sounds like your VPN is killing idle connections. `kubefwd` does not re-connect for a few reasons: 1) It does not know the forward is broken until you try to communicate over it; 2) A TCP failure does not necessarily mean that the forward itself is broken.
