### ISSUE TITLE
Multiple clusters Support

### ISSUE THREAD

**Issue by collbrain** [txn2/kubefwd#165]
Does Kubefwd support multiple clusters?. 

How does it work if the same workload runs on two or more different clusters and exposing the same port?

**Comment by Tarick** [comment]
It doesn't and it would be really problematic to do so even if it would - the same service name with namespace can't be duplicated in hosts file. You can start 2 copies of kubefwd that would use different clusters  - use KUBECONFIG env variable to specify needed config file with cluster. However kubefwd manages hosts file and it will be 2 consecutive replacements of the file that will leave it in inconsistent state at some point.

**Comment by Tarick** [comment]
There is also `-x, --context strings` parameter to `kubefwd svc` , so one may use that.

**Comment by cjimti** [comment]
@collbrain should would work fine. `kubefwd` uses separate ip addresses for each forward and will only create short named entires for the first cluster. The context name of the second cluster is appended. 

I forward multiple clusters often.
