### ISSUE TITLE
Always append context name to hosts file in multi cluster 

### ISSUE THREAD

**Issue by bjsee** [txn2/kubefwd#167]
We have different clusters with same services, for example a service named config-server. When I know start kubefwd with following command:
`sudo kubefwd svc -x hit-qs -x hit-stage`
the hosts file generated looks like this:
`
127.1.27.4       config-server config-server.default config-server.default.svc config-server.default.svc.cluster.local config-server.default.hit-qs config-server.default.svc.hit-qs config-server.default.svc.cluster.hit-qs`
`127.2.27.45      config-server.hit-stage config-server.default.hit-stage config-server.default.svc.hit-stage config-server.default.svc.cluster.hit-stage`

It would be good if first entry would (additionaly) also contain `config-server.hit-qs` in the first row.
So this way we could say, that by convention the config-server service is available under `config-server` + k8s context name

**Comment by cjimti** [comment]
I know for me this would have the possibility of colliding with namespaces. I have a context called **acmecorp** which points to my  **acmecorp** production cluster, and on my dev cluster (context **dev**) I have a namespace called  **acmecorp**. 

I can access service **x** with the fully qualified **x.acmecorp,svc.cluster.dev** (or **x.acmecorp,svc.cluster.local** if it's the fist in the parameter list) and **x.acmecorp,svc.cluster.acmecorp**. Also, when developing, my service discovery is typically looking for **x.acmecorp,svc.cluster.local** or **x.acmecorp** or just **x** in which case it would find it in the first cluster in the list.
 
The goal is to avoid collisions and to remain as close to Kubernetes internal service DNS as possible.
