### ISSUE TITLE
Standardise release tags

### ISSUE THREAD

**Issue by glitchcrab** [txn2/kubefwd#172]
Would it be possible to pick a release tag scheme and stick to it for future releases? 

I package kubefwd for Arch's AUR and this relies on predictable download URLs for the release assets. With `1.17.4` the release url changed to include a `v` prefix - will this be the standard going forward, or was it just a one-off?

**Comment by cjimti** [comment]
It was a mistake.

**Comment by glitchcrab** [comment]
great, thanks for the clarification!
