### ISSUE TITLE
Is there a way to get more debugging logs from kubefwd?

### ISSUE THREAD

**Issue by xbeta** [txn2/kubefwd#179]
I tried it with `--verbose` and without, don't get much information. Trying to debug the error below.

```
sudo kubefwd svc --verbose -n grpc-services
Password:
INFO[17:59:20]  _          _           __             _
INFO[17:59:20] | | ___   _| |__   ___ / _|_      ____| |
INFO[17:59:20] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
INFO[17:59:20] |   <| |_| | |_) |  __/  _|\ V  V / (_| |
INFO[17:59:20] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
INFO[17:59:20]
INFO[17:59:20] Version 1.18.0
INFO[17:59:20] https://github.com/txn2/kubefwd
INFO[17:59:20]
INFO[17:59:20] Press [Ctrl-C] to stop forwarding.
INFO[17:59:20] 'cat /etc/hosts' to see all host entries.
INFO[17:59:20] Loaded hosts file /etc/hosts
INFO[17:59:20] HostFile management: Original hosts backup already exists at /Users/xbeta/hosts.original
FATA[17:59:22] Error connecting to k8s cluster: the server has asked for the client to provide credentials
```

**Comment by cjimti** [comment]
@xbeta have you tried `sudo -e` ? otherwise you might need to supply the path to the `kubectl` config with `-c /Users/xbeta/.kube/config.

**Comment by xbeta** [comment]
> @xbeta have you tried `sudo -e` ? otherwise you might need to supply the path to the `kubectl` config with `-c /Users/xbeta/.kube/config.

Do you mean `sudo -E` with a capitalize E?

May I know why is this necessary to run `kubefwd` ?

**Comment by cjimti** [comment]
@xbeta sorry yes I meant `-E (preserve environment)`. `kubefwd` uses [kubernetes/client-go](https://github.com/kubernetes/client-go) which will look in your home directory for `.kube/config`. I assume you have `kubectl` installed and able to access a cluster with it. 

The error you see `"Error connecting to k8s cluster: the server has asked for the client to provide credentials"` seems that eighter something is wrong with your `.kube/config` or it's using the wrong context.
