### ISSUE TITLE
Runtime: error copying from local connection to remote stream

### ISSUE THREAD

**Issue by hoyindev** [txn2/kubefwd#180]
Port forward services from the cloud and when I try to call the API from my local Go program to one service, sometimes it works fine but more often I got this error:
````
[31mERRO[0m[22:50:49] Runtime: error copying from local connection to remote stream: read tcp4 127.1.27.17:8080->127.0.0.1:51561: wsarecv: An existing connection was forcibly closed by the remote host.
````

Does anyone have this issue as well? Is there any way to solve this problem? (I am using window and google cloud SDK shell)

**Comment by dantheman999301** [comment]
I get this error a lot but it still continues to work. I don't know if that's because the `HttpClient` in dotnet is just refreshing the connection.

**Comment by cjimti** [comment]
I'm not sure there is anything `kubefwd` can do about this. Do you have connection issues when using `'kubectl` port forwarding?

**Comment by hoyindev** [comment]
> I'm not sure there is anything `kubefwd` can do about this. Do you have connection issues when using `'kubectl` port forwarding?

no, I don't have this issue using kubectl port forwarding.

**Comment by cjimti** [comment]
Unless anyone has more information on the WSARecv function (winsock2.h) and why it has trouble with `kubefwd` and not `kubectl port-forward` I am closing this. `kubefwd` uses the same Kubernetes client library as `kubectl port-forward`.

**Comment by danieltaub96** [comment]
I'm experiencing this issue as well on osx 11,
Using kubectl working just fine, when using the kubefwd it actually forwarding all the services, but on request I get the same error

**Comment by RuBAN-GT** [comment]
The similar problem for me:

> ERRO[10:03:23] Runtime: error copying from remote stream to local connection: readfrom tcp4 127.1.28.3:80->127.1.28.3:56779: write tcp4 127.1.28.3:80->127.1.28.3:56779: write: broken pipe

**Comment by cjimti** [comment]
![ukraine](https://user-images.githubusercontent.com/356698/159857129-80ba2005-e609-46f5-b8e2-f26bd98315bb.jpeg)
