### ISSUE TITLE
Empty hosts file after killing kubefwd

### ISSUE THREAD

**Issue by josephgardner** [txn2/kubefwd#181]
This seems to have started suddenly, but when I use kubefwd in either vscode or iterm on osx, the `/etc/hosts` file is empty. I have to manually restore the backup from `~/hosts.original`

```
➜ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1        localhost
255.255.255.255  broadcasthost
::1              localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1        kubernetes.docker.internal
```

```
➜ sudo -E kubefwd svc -l app=myapp
INFO[17:36:44]  _          _           __             _     
INFO[17:36:44] | | ___   _| |__   ___ / _|_      ____| |    
INFO[17:36:44] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |    
INFO[17:36:44] |   <| |_| | |_) |  __/  _|\ V  V / (_| |    
INFO[17:36:44] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|    
INFO[17:36:44]                                              
INFO[17:36:44] Version 1.18.0                               
INFO[17:36:44] https://github.com/txn2/kubefwd              
INFO[17:36:44]                                              
INFO[17:36:44] Press [Ctrl-C] to stop forwarding.           
INFO[17:36:44] 'cat /etc/hosts' to see all host entries.    
INFO[17:36:44] Loaded hosts file /etc/hosts                 
INFO[17:36:44] HostFile management: Backing up your original hosts file /etc/hosts to /Users/joseph.gardner/hosts.original 
INFO[17:36:44] Using namespace default from current context minikube. 
INFO[17:36:44] Successfully connected context: minikube     
INFO[17:36:44] Port-Forward: 127.1.27.1 environment-sample:5432 to pod environment-sample-0:5432 
INFO[17:36:44] Port-Forward: 127.1.27.1 environment-sample:8443 to pod environment-sample-0:8443
```

```
➜ cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1        localhost
255.255.255.255  broadcasthost
::1              localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1        kubernetes.docker.internal
127.1.27.1       environment-sample environment-sample.default environment-sample.default.svc environment-sample.default.svc.cluster.local environment-sample.default.minikube environment-sample.default.svc.minikube environment-sample.default.svc.cluster.minikube
```
```
^CINFO[17:38:08] Received shutdown signal                     
INFO[17:38:08] Stopped watching Service events in namespace default in minikube context 
INFO[17:38:08] Clean exit                                   

➜ cat /etc/hosts
➜ 
```

If I run the `kubefwd` command again,

```
➜ cat /etc/hosts
127.1.27.1       environment-sample environment-sample.default environment-sample.default.svc environment-sample.default.svc.cluster.local environment-sample.default.minikube environment-sample.default.svc.minikube environment-sample.default.svc.cluster.minikube
```

**Comment by cjimti** [comment]
This does not happen for me or anyone on my team (mid of windows, mac and Ubuntu users) and I have no reports of it happening to anyone else. Do you have any more details that can help me reproduce it? Are you running any other software that manages your `/etc/hosts`?

**Comment by flupec** [comment]
There is definitely something wrong with the hosts file. I do not know about other platforms, but on Windows the state of this file is not entirely determined (possibly due to firewall programs and other things).
After following log message: `ERRO[16:37:32] Error saving /etc/hosts: open C:\Windows\System32\Drivers\etc\hosts: The process cannot access the file because it is being used by another process.`
host file contains unremoved lines.

I think it's necessary to lock this file on OS level

**Comment by cjimti** [comment]
I use primarily use Ubuntu for my main development workstation and have a mac I do some work on. I don't use Windows and it seems this is an issue with it. I would need to understand the problem and how `kubefwd` is causing it. Kuberfwd reads the `/etc/hosts` file and writes out a new one when adding and removing services. I don't know how a blank `/etc/hosts` file is being written. 

> I think it's necessary to lock this file on OS level

What additional locking would need to happen for Windows? `kubefwd` uses https://github.com/txn2/txeh for `/etc/hosts` management. 

Here is the read file: -> https://github.com/txn2/txeh/blob/09e29537ecce61eafea9f21a18fd2f5e272074a6/txeh.go#L293
Here is the save file: -> https://github.com/txn2/txeh/blob/09e29537ecce61eafea9f21a18fd2f5e272074a6/txeh.go#L93
