### ISSUE TITLE
Does it auto connect if service disconnects?

### ISSUE THREAD

**Issue by smartaquarius10** [txn2/kubefwd#183]
Team,

In majority cases, the port forward service auto disconnects after few hours or days. Does this application application automatically reconnect in such cases.

For eg. we have jenkins hosted in kubernetes. To connect windows slave agents with jenkins we have to enable port forwarding in production. After few days, connection automatically disconnects which needs a custom coding of looping mechanism either using powershell or bat script or any custom console application or task scheduler.

Does kubefwd application resolves this problem and auto reconnects with the services. Please help.

Thank you

**Comment by cjimti** [comment]
@smartaquarius10 `kubefwd` does not monitor the forwarded connection. `kubefwd` is designed for the temporary forwarding of services to aid in local development.
