### ISSUE TITLE
[Feature Request] Forward via ethernet network interface 

### ISSUE THREAD

**Issue by avarabyeu** [txn2/kubefwd#186]
Idea: Multiple services are proxied via kubefwd started in docker. I would like other container to be able to access forwarded service. Since kubefwd creates lopback interfaces, there is no way to access proxied service over network. 
Is there any way to get forwarded services available over network?

**Comment by cjimti** [comment]
`kubefwd` just needs access to create IPs on whatever network interface it has access to. Have you tried giving the container access to the host network? (BTW this could be a big security issue depending on your environment).

**Comment by Charg** [comment]
> `kubefwd` just needs access to create IPs on whatever network interface it has access to. Have you tried giving the container access to the host network? (BTW this could be a big security issue depending on your environment).

When running `kubefwd` in docker it would be nice to have the ability to map a services ports to the address `0.0.0.0`. That way there's no need to mess with the hosts network. I can see issues with overlapping ports depending on what people have mapped on their pods/services.

**Comment by cjimti** [comment]
This would be an anti-pattern for `kubefwd` as many of us have dozens+ of services running on common ports. Using loop-backs and `/etc/hosts` to approximate the Kubernetes service abstraction is the core feature of `kubefwd`. I think what you are trying to accomplish might be better served with `kubectl port-forward` or a proxy solution.
