### ISSUE TITLE
error forwarding port after pod restart

### ISSUE THREAD

**Issue by jdechicchis** [txn2/kubefwd#188]
I see the following error when trying to `curl myservice:8080` after restarting a service's pod. 
```
ERRO[15:03:36] Runtime: an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 16a8ad2a1690f8027bd29d67765ca79236db2fac665624a681e78f756be7c9bd, uid : failed to find sandbox "16a8ad2a1690f8027bd29d67765ca79236db2fac665624a681e78f756be7c9bd" in store: not found
```

I'm using kind for my cluster. I'm curious whether this is expected or not and if it isn't expected if there are plans to fix this issue. I think restarting pods is a very common operation during kubernetes local development.

**Comment by fgblomqvist** [comment]
Might be a duplicate of #169 (or at least related)

**Comment by cjimti** [comment]
please see my comment on #169 https://github.com/txn2/kubefwd/issues/169#issuecomment-875936713
