### ISSUE TITLE
Kubefwd doesnt start correctly

### ISSUE THREAD

**Issue by pedrofelix00** [txn2/kubefwd#190]
![Screenshot from 2021-07-01 16-42-38](https://user-images.githubusercontent.com/86728401/124152457-7305c780-da8b-11eb-8592-c198d1ba1cc2.png)

Cant use kubefwd without authorization, but when sudo is used, it shows that kubefwd doesnt exist.

**Comment by cjimti** [comment]
This is not an issue with `kubefwd`, your root user (when using sudo) does not have `kubefwd` in it's path.
