### ISSUE TITLE
Untag kubectl from the repo?

### ISSUE THREAD

**Issue by ahmetb** [txn2/kubefwd#192]
Do you mind untagging `kubectl` tag from the repo since the project is not related to kubectl.

**Comment by cjimti** [comment]
It is however an alternative to `kubectl port-forward`.

**Comment by cjimti** [comment]
@ahmetb I removed it but may consider re-adding it after reading more about GitHub **Topics**. 

https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics#about-topics

> Repository admins can add any topics they'd like to a repository. Helpful topics to classify a repository include the repository's intended purpose, subject area, community, or language.  

I want to respect the `kubectl` community but also don't see how `kubectl` as a topic is confusing people.  Can you point to any community documentation or etiquette guide on the matter? IMO `kubefwd` is within the **subject area** of kubectl including shared config and capabilities.

**Comment by ahmetb** [comment]
There's no etiquette I was referring to, just that this tool didn't seem like it is specifically about kubectl. No worries.

**Comment by cjimti** [comment]
80% of the install traffic comes from Google searches related to `kubectl port-forward`. There were very few alternative methods at the time I wrote it, and saw `kubefwd` as a complementary utility. There was never an intention to mislead anyone.
