### ISSUE TITLE
v1.20 - No kubecontext switch flags available

### ISSUE THREAD

**Issue by ivan046** [txn2/kubefwd#196]
-x and --context flags are absent in the latest 1.20 release. Please get them back.

**Comment by flupec** [comment]
@ivan046 
It works for me. Check if you specifying context name (and not, for example, cluster) and correct kubeconfig file that contains specified context.

According to the source code, these parameters were not affected when the new version was released.

If you are sure of the correctness of the input parameters, then please provide a test case.

**Comment by pia-drcash** [comment]
@flupec thanks a lot. My fault, I've forgotten. Its
`kubefwd svc -h` not `kubefwd -h` :)
Closing the issue.
