### ISSUE TITLE
Procedure to enable communication with ClusterIP using kubefwd

### ISSUE THREAD

**Issue by nagannv** [txn2/kubefwd#203]
We are using the kubefwd utility to access k8s cluster IP services outside the k8s cluster from a ubuntu VM. The tool is really helpful in providing the access cluster IP services, thankful to you for making such a useful utility.

our objective in using kubefwd utility to enable communication between ubuntu VM ( outside the K8S cluster) and servicers on K8S services , and to run some shell scripts on the K8S services.

The shell scripts firsts configures DB instances (i.e crunchy db postgres operator DB pod instances) on K8S,  then apply the network policy on K8S cluster after the name resolution (the scripts runs dig command  for DB service name resolution ), the network polices required to enable communication between application services with postgres DB services

since the kubefwd tool updating the etc/hosts  with IPs 127.1.27.X , the name resolution of the DB instance resolving to 127.1.27.X , therefore  network policies are configured 127.1.27.X IP range instead of DB service ClusterIP, resulting the application services failing to make proper communication with DB services, to unblock ourselves from this situation as workaround we are updating network policy manually replacing the 127.1.27.x ( which got configured by the scripts after executing the dig command)  with 0.0.0.0

want to check whether kubefwd utility can populate the /etc/hosts with actual cluster IP and enable kubefwd communication with ClusterIP, this helps to populate the network polices exactly with required DB service ClusterIP

Also, we have configured kube-dns as load-balancer service, update dnsmasq.conf file with kube-dns loadbalancer as DNS forwarder to resolve the k8S Services, with this the name resolution with help of dnsmasq happening with ClusterIP ( until we restart the dnsmasq service), but the sql communication to PGO DB services is failing from Ubututu VM .

Once after restarting dnsmasq service, name resolution is happing with 127.1.27.X IP,  and the sql communication is happing dns, but this needs the adjustment of network policies by replacing 127.1.27.x with 0.0.0.0.

Previous to implementing of kubefwd configuration, we have made use the DB instances as LoadBalacer service with Bind9 for name resolution. the kubefwd greatly reduced efforts, but needs to adjust the network policy. 

looking for your input on whether kubefwd helps us in using ClusterIP instead of 127.1.27.X IP  to enable the communication with required actual  ClusterIP   rather adjusting manually with 0.0.0.0 range

ubuntu@prodagdrgen3adminvm:~$ kubectl get svc -n pgo
NAME                              TYPE          CLUSTER-IP        EXTERNAL-IP     PORT(S)                                           AGE
pig                                     ClusterIP   10.254.52.23      <none>           2022/TCP,5432/TCP                          78m
pi-backrest-shared-repo   ClusterIP   10.254.227.211   <none>          2022/TCP                                          78m
postgres-operator             ClusterIP   10.254.150.109   <none>          8443/TCP,4171/TCP,4150/TCP          81m

cat /etc/dnsmasq.conf    
interface=lo
bind-interfaces
listen-address=127.0.0.1
server=/cluster.local/192.168.1.150  --------> kube-dns SVC as loadbalancer
server=8.8.8.8

nslookup pig.pgo.svc.cluster.local   --------> Host name lookup of the desired DB services
Server:         127.0.0.1
Address:        127.0.0.1#53
Name:   pig.pgo.svc.cluster.local   
Address: 10.254.52.23  --------> Resolving to ClusterIP as expected

ubuntu@prodagdrgen3adminvm:~$ jobs  -------> run the kubefwd in the back-end
[1]+  Running                 sudo kubefwd svc -n pgo &

cat /etc/hosts     -------> /etc/hosts entries after executing  kubefwd
127.1.27.1       pig-backrest-shared-repo pig-backrest-shared-repo.pgo pig-backrest-shared-repo.pgo.svc pig-backrest-shared-repo.pgo.svc.cluster.local pig-backrest-shared-repo.pgo.default pig-backrest-shared-repo.pgo.svc.default pig-backrest-shared-repo.pgo.svc.cluster.default
127.1.27.2       pig pig.pgo pig.pgo.svc pig.pgo.svc.cluster.local pig.pgo.default pig.pgo.svc.default pig.pgo.svc.cluster.default
127.1.27.3       postgres-operator postgres-operator.pgo postgres-operator.pgo.svc postgres-operator.pgo.svc.cluster.local postgres-operator.pgo.default postgres-operator.pgo.svc.default postgres-operator.pgo.svc.cluster.default

$ psql --host=pig.pgo.svc.cluster.local --port=5432  --username="xxxxx" --password --dbname=pig -------> try establish sql connection from Ubuntu VM to DB service with hostname resolved CluserIP 
Password for user xxxxxx:
^C            -------> No connection, cancel the command
ubuntu@prodagdrgen3adminvm:~$ ping pig.pgo.svc.cluster.local -------> Ping from Ubuntu VM to DB service with hostname resolved CluserIP 
PING pig.pgo.svc.cluster.local (10.254.52.23) 56(84) bytes of data.
From XXXXXXXX (103.XXX.XXX.1) icmp_seq=1 Destination Host Unreachable
From XXXXXXXX (103.XXX.XXX.1) icmp_seq=1 Destination Host Unreachable
From XXXXXXXX (103.XXX.XXX.1) icmp_seq=1 Destination Host Unreachable
^C
--- pig.pgo.svc.cluster.local ping statistics ---
6 packets transmitted, 0 received, +3 errors, 100% packet loss, time 5093ms
pipe 3

$ sudo systemctl restart dnsmasq   ---------> restart the dnsmasq service

$ nslookup pig.pgo.svc.cluster.local --------> Host name lookup of the desired DB services
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:   pig.pgo.svc.cluster.local
Address: 127.1.27.2 --------> resolving to 127.1.27.2 to /etc/host entry

$ ping pig.pgo.svc.cluster.local --------> ng from Ubuntu VM to DB service with hostname resolved to 127.1.27.2
PING pig.pgo.svc.cluster.local (127.1.27.2) 56(84) bytes of data.
64 bytes from fence (127.1.27.2): icmp_seq=1 ttl=64 time=0.040 ms

ubuntu@prodagdrgen3adminvm:~$ psql --host=pig.pgo.svc.cluster.local --port=5432  --username="xxxxx" --password --dbname=pig
Password for user xxxx:
psql (10.18 (Ubuntu 10.18-0ubuntu0.18.04.1), server 13.3)
WARNING: psql major version 10, server major version 13.
         Some psql features might not work.
Type "help" for help.

pig=#

**Comment by cjimti** [comment]
@nagannv There is a lot here so forgive me if I misunderstand. Kuberfwd can only port-froward to a Pod, as far as I am aware there is no way to port-forward to a ClusterIP.  Kubefwd uses `127.` addresses to bind its port-forward to since they are unlikely to conflict with local network services as they are reserved for loopback testing. Kubefwd does not create any port-forward on `0.0.0.0` as this represents all loopbacks, therefore there could not be more than one of each port number, So `main-db:5432on 0.0.0.0` and `replica-db:5432 on 0.0.0.0` would conflict.

**Comment by nagannv** [comment]
@cjimti 
Thank you for your kind response. now I understood the significance of 127.X. since there is no way to use the actual clusterIP for foring and have the clicuterIP in the /etc/hosts, I will continue to use the work-around.

**Comment by ndj888** [comment]
@nagannv This may not be a problem that kubefwd is trying to solve. You want to use host ip to access the service, maybe you should consider iptables SNAT.

`ex:
iptables -t nat -A POSTOUTING -s 127.1.27.0/24 -j SNAT --to-source (192.168.0.xx you host net ip) -o eth0 (you host net interface)
`
In this way, it can use the host's IP communication, but this will introduce additional complexity. iptables is a network tool of the linux kernel, with it you can control the network.
