### ISSUE TITLE
Hang when specifying labels

### ISSUE THREAD

**Issue by stobias123** [txn2/kubefwd#206]
Love the tool! 

Running into a minor issue where I'm trying to forward based on labels. The below command ends up hanging after connecting to context.... everything works fine when I don't use labels.

```
sudo -E kubefwd svc -n streamtracker-dev -l app=postgresql,app=redis,common.k8s.elastic.co/type=elasticsearch,common.k8s.elastic.co/type=kibana
```

**Comment by cjimti** [comment]
Looks like there might be a misunderstanding. I assume you don't have any pods with all these labels: `"app=postgresql,app=redis,common.k8s.elastic.co/type=elasticsearch,common.k8s.elastic.co/type=kibana`.

The expression above is an equality-based ("and" ) operation. Like `kubectl`, `kubefwd` also supports set-based selectors, example: `-l "app in (postgresql,redis)"`

Checkout the following documentation:

https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering
