### ISSUE TITLE
Forwards multiple services with multiple selectors in different namespaces

### ISSUE THREAD

**Issue by badaljain** [txn2/kubefwd#215]
Hi all,

I have a requirement of forwarding multiple services with multiple selectors as below:
`sudo --preserve-env kubefwd services -l "app in (serviceA, serviceB, serviceC),app.kubernetes.io/name=flagsmith" -n services -n flagsmith`

my service A, B and C belong to services namespace and they have the label called `app` and the flagsmith service belongs to another namespace called `flagsmith` and doesn't have `app` selector, rather it has `app.kubernetes.io/name` selector. I am not able to forward these services.

Please advise!
TIA

**Comment by cjimti** [comment]
Are you able to just froward all services in both namespaces? You only need the selector if you have a very large number of services.

Additional selector examples: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api

**Comment by badaljain** [comment]
Yep, I am able to forward all the services in both name spaces.. i have around 14 services and I actually need port forwarding for just 4.

**Comment by cjimti** [comment]
You'll have to forward all of them if there is no common selector.

**Comment by badaljain77** [comment]
hmn, I now have a common selector but different namespaces.. still doesn't work:
sudo --preserve-env kubefwd services -l "app in (serviceA, serviceB, serviceC, flagsmith-ui,flagsmith-api)" -n services -n flagsmith

**Comment by cjimti** [comment]
@badaljain does the same selector work with `kubectl`? `kubefwd` uses the same client library as `kubectl`

**Comment by badaljain77** [comment]
Apologies the `flagsmith-ui,flagsmith-api` are pod app labels and not service app labels. thank you for confirming the namespace usage.
