### ISSUE TITLE
kubefwd doesn't refresh cluster state

### ISSUE THREAD

**Issue by nikitamikhaylov** [txn2/kubefwd#217]
Hi! I tried to use kubefwd with Minikube and faced with a problem, that kubefwd doesn't refresh state on any changes in cluster (e.g. adding new replicas in stateful set and so on). Is it intended? Or do I have to execute kubefwd with timeout / restart manually?

**Comment by ndj888** [comment]
Currently kubefwd does not detect cluster status changes from kubelet, but adapts itself.

**Comment by cjimti** [comment]
@nikitamikhaylov `kubefwd` is intended for temporary forwarding during local development. If your cluster state changes while you are developing you will need to stop and restart it.
