### ISSUE TITLE
Add http:// to logs for easier access

### ISSUE THREAD

**Issue by bsgrigorov** [txn2/kubefwd#219]
Please add http:// right before service names for easier link opening.

This would be very helpful for Chrome, which does not trust local /etc/hosts dns entries automatically and instead does a google search when you write just the service name.

**Comment by cjimti** [comment]
This would be assuming that all service-name/port combinations are web pages or even the HTTP protocol, and even then it would not know if it should be `http` or `https`. I know for myself and a lot of developers that use `kubefwd` it would be strange and misleading to see the log output using `http://` in front of our mostly backend services. 

`kubefwd` is intended for any services that listen on TCP ports, including backend APIs, microservices, and databases all of which would look very misleading to add an `http://` in front of them.

**Comment by bsgrigorov** [comment]
@cjimti can this be added based on the port that is served then? If it's 80 http and so on.

**Comment by cjimti** [comment]
@bsgrigorov you might want to try something like this:

 `sudo kubefwd svc -n somens | sed -E 's/(127.[0-9|.]+\ )/\1 http:\/\//'

You could also alias it.
