### ISSUE TITLE
IP addresses change suddenly

### ISSUE THREAD

**Issue by mrumpf** [txn2/kubefwd#22]
When I was connecting to my cluster yesterday, my Grafane dashboard was having IP 127.1.27.7.
When I connected this morning, it had 127.1.27.8.

One idea to avoid this might be some algorithm, which derives the IP address from the name of the service, e.g. creating a md5 hash out of, creating a value out of it and taking a modulo 255 to derive the last digit of the IP address.
The consequence would be that the IP addresses are spread over the full range.
But at least the IP would remain the same, as long as the name of the service does not change.

**Comment by cjimti** [comment]
I did not really consider anyone needing persistent IP addresses cross-sessions. I am curious about your use case.

Interesting proposal but a lot to think about. It would also need to do the same with the cluster (context) and namespace to be consistent. I have multiple clusters and multiple namespaces. Also, might need to consider cluster federation. 

Maybe something like your suggestion 127.CLUSTER.NAMESPACE.SERVICE ?

**Comment by cjimti** [comment]
optimizing the output is a great idea, maybe even suppressing the output of the local IP used and having a verbose option for those interested. Technically it's not essential information and prone to confuse people.

**Comment by cjimti** [comment]
@mrumpf kubefwd 1.4.10 now displays the host and port first to help avoid confusion. Example **Forwarding: api4-nginx:80 to pod api4-678db48c86-llvr6:80**

use the `-v` verbose option if you want it to log the local IP being used.
