### ISSUE TITLE
Intermittent connection errors

### ISSUE THREAD

**Issue by stefanbethke** [txn2/kubefwd#222]
I have kubefwd 1.22.0 running on an M1 Mac, talking to a k3d cluster on my laptop. I have a web server running in the cluster (nginx) that has a service on port 8080, with the pod listening on port 80.

Every other request fails like this:
```
$ curl -v http://blob-server:8080/86/c6/86c6036b31986d087f6f38c8bfe4bf47
*   Trying 127.1.27.6:8080...
* Connected to blob-server (127.1.27.6) port 8080 (#0)
> GET /86/c6/86c6036b31986d087f6f38c8bfe4bf47 HTTP/1.1
> Host: blob-server:8080
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```
kubefwd shows this:
```
ERRO[10:14:28] Runtime: error creating error stream for port 8080 -> 80: Timeout occured 
```

Some requests go through as expected:
```
$ curl -v http://blob-server:8080/86/c6/86c6036b31986d087f6f38c8bfe4bf47
*   Trying 127.1.27.10:8080...
* Connected to blob-server (127.1.27.10) port 8080 (#0)
> GET /86/c6/86c6036b31986d087f6f38c8bfe4bf47 HTTP/1.1
> Host: blob-server:8080
> User-Agent: curl/7.77.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.6
< Date: Thu, 10 Mar 2022 09:16:55 GMT
< Content-Type: application/octet-stream
< Content-Length: 498223
< Last-Modified: Thu, 24 Feb 2022 07:13:51 GMT
< Connection: keep-alive
< ETag: "6217302f-79a2f"
< Accept-Ranges: bytes
< 
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.
* Failure writing output to destination
* Closing connection 0
```

I'm not sure how to debug this.

**Comment by cjimti** [comment]
@stefanbethke I moved away from Mac (to Linux) many years ago and no longer have the ability to debug Mac issues if this is one. I'll leave this open a bit longer to see if anyone else has this issue and can chime in.

**Comment by stefanbethke** [comment]
Thanks for that. At this point, I can't say for sure where the problem originates, and it's possible that the issue is caused by Eset Endpoint Security trying to inspect the traffic (something I have no control over, unfortunately).

**Comment by stefanbethke** [comment]
As I said, I have no control over that. I will need to talk to the IT department to try and debug this.
