### ISSUE TITLE
Documentation for noobs

### ISSUE THREAD

**Issue by gonzojive** [txn2/kubefwd#228]
I have been running the following for forwarding commands for local development:

```shell
kubectl port-forward --namespace default service/cockroachdb-public 5010:8080 5011:26257
kubectl port-forward --namespace kube-system service/registry 5000:80
```

It would be nice if the documentation made it clear how to achieve the same using a single command. Some clarifications in the documentation would be

1. kubectl uses `service/blah` to name services. What's the equivalent with kubefwd?
2. What is the point of /etc/hosts entries for services, and can this be disabled? (I know already that all services have hostname localhost.)
3. I only want to port forward a small set of ports for select services. Can I disable the default logic of "forward ports for all services?"

**Comment by cjimti** [comment]
@gonzojive Issuing the command `kubefwd svc -h` will give you a few examples, the available flags, and a short description of each one.

> 1. kubectl uses service/blah to name services. What's the equivalent with kubefwd?

`sudo kubefwd svc blah -n default` 

> 2. What is the point of /etc/hosts entries for services, and can this be disabled? (I know already that all services have hostname localhost.)

`kubefwd` does not use `localhost`. It assigns each service a separate local IP and adds an `/etc/hosts` entry with the service name pointing to that IP. If your `service/blah` exposes port `1234` then you would be able to access it locally via `blah:1234`. You can not disable the `/etc/hosts/` entries as this is the central feature and reason for `kubefwd`.  `kubefwd` is designed to mimic internal cluster access to services.

> 3. I only want to port forward a small set of ports for select services. Can I disable the default logic of "forward ports for all services?"

Yes, `kubefwd` offers [Field Selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors/) with the flag `-l, --selector string` and uses the same code `kubectl` does for this. 

If you only need access to a couple of services and don't care about the names and ports then `kubectl` is the right tool. 

However, `kubefwd` is designed for the following scenario which is common with my team: 

We have software code under development that communicates with the following services `auth:80`, `api:80` and `db:3306`. Before we can run this code on our local workstations we would need to manually port forward each of these services to `localhost` and give them unique port numbers. We would then have to configure our application to use `localhost:cutom_port` for each of them. However, if the expected hostname and ports already exists we don't need to do any of that.  If we use `kubefwd` we get `auth:80`, `api:80` and `db:3306` on our local machine and don't need to worry about a custom configuration for each connection.


![](https://camo.githubusercontent.com/6c35bdcb997d0b6456109962e42d6bdee9ed31a524f8b6b830e8c39e8e9fc901/68747470733a2f2f6d6b2e696d74692e636f2f696d616765732f636f6e74656e742f6b7562656677642d6e65742e706e67)
