### ISSUE TITLE
Multiple localhost entries in /etc/hosts

### ISSUE THREAD

**Issue by mrumpf** [txn2/kubefwd#23]
I had the issue several times that the /etc/hosts file had been modified by kubefwd in a way that prevented it to start again:
````
Can not load /etc/hosts
2018/11/22 11:26:27 Duplicate hostname entry for localhost -> ::1
````

The /etc/hosts had the following entry (up to 4 times once)
````
::1 localhost localhost ... localhost
````

I had the impression that this happened when starting it accidentally a second time for the same cluster, but I could not reproduce the issue in a new test.

**Comment by cjimti** [comment]
kubefwd should check if another instance is running and inform the user.  I've added this to the 1.4.x milestone and will make it a priority.

**Comment by mrumpf** [comment]
It was happening again when I left work, closed the macbook and opened it again back home. It was showing a few errors, when I hit CTRL-C in the iTerm window, it stopped correctly. When trying to restart it I got the error above.

````
E1123 20:02:52.823324   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:02:52.823324   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:02:52.823349   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:02:52.823348   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:02:52.823396   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:02:52.823347   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:03:22.833819   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:03:22.836292   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:03:22.838176   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:03:22.838187   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:03:22.839097   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
E1123 20:03:22.839101   83015 portforward.go:292] error creating error stream for port 80 -> 3000: Timeout occured
^CStopped ...

Done...
````

Starting again resulted in the error above:
````
$ kubefwd ...
Password:

 _          _           __             _
| | ___   _| |__   ___ / _|_      ____| |
| |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
|   <| |_| | |_) |  __/  _|\ V  V / (_| |
|_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|

Press [Ctrl-C] to stop forwarding.
'cat /etc/hosts' to see all host entries.
Loading hosts file /etc/hosts
Can not load /etc/hosts
2018/11/23 20:03:27 Duplicate hostname entry for localhost -> ::1
````

**Comment by cjimti** [comment]
Looks like running multiple instances at the same time may have put your /etc/hosts in a state that causes an error when the hostess lib parses it. You could restore /etc/hosts from the /etc/hosts.original or just edit out the offending entry (Duplicate hostname entry for localhost). 

I think a sensible feature would be a prevention or warning about running multiple instances.

**Comment by mrumpf** [comment]
It is also not about running multiple instances. I just had one instance running all the time, but still the second "localhost" entry started showing up.
Maybe an idea is to dump the file content each time it gets modified in a debug log and we will see when the second entry gets added.

**Comment by cjimti** [comment]
Since it's currently logging to standard out I can add a `--verbose` option, this should help track down any other anomalies.

**Comment by cjimti** [comment]
@mrumpf kubefwd 1.4.10 now checks for "Duplicate hostname entry for localhost -> ::1" and attempts to correct the issue. The unlying issue with hostess should still be addressed but hopefully, this will be an acceptable workaround for the time being.
