### ISSUE TITLE
Possible to forward non-service address that are only accessible inside k8s?

### ISSUE THREAD

**Issue by shiyao-afterpay** [txn2/kubefwd#232]
My use case is, I have some Kafka broker address, which are whitelisted to be only accessible from within k8s.

I wonder if kubefwd has the feature of forwarding not only the normal k8s services, but also forwarding access to these external endpoints like through some configuration files?

**Comment by cjimti** [comment]
`kubefwd` can only port-forward to pods (containers). You would need to set up a pod that proxies your endpoints if you want to use `kubefwd`.
