### ISSUE TITLE
Error when parsing the server version

### ISSUE THREAD

**Issue by safderun** [txn2/kubefwd#236]
Hi, when I run kubefwd svc -n production, I get this error: 

> INFO[15:21:35]  _          _           __             _     
> INFO[15:21:35] | | ___   _| |__   ___ / _|_      ____| |    
> INFO[15:21:35] | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |    
> INFO[15:21:35] |   <| |_| | |_) |  __/  _|\ V  V / (_| |    
> INFO[15:21:35] |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|    
> INFO[15:21:35]                                              
> INFO[15:21:35] Version 1.22.3                               
> INFO[15:21:35] https://github.com/txn2/kubefwd              
> INFO[15:21:35]                                              
> INFO[15:21:35] Press [Ctrl-C] to stop forwarding.           
> INFO[15:21:35] 'cat /etc/hosts' to see all host entries.    
> INFO[15:21:35] Loaded hosts file /etc/hosts                 
> INFO[15:21:35] HostFile management: Original hosts backup already exists at /root/hosts.original 
> FATA[15:21:35] Error connecting to k8s cluster: unable to parse the server version: invalid character '<' looking for beginning of value

**Comment by cjimti** [comment]
@safderun looks like you are probably getting HTML from wherever your context is pointed, so I assume that `kubefwd` is not getting a usable configuration. Can you access your cluster with `kubectl`? What is the path to your `kubectl` config file?
