### ISSUE TITLE
Option to display created Local Domains

### ISSUE THREAD

**Issue by MarkCupitt** [txn2/kubefwd#250]
This is a wonderful tool, was amazed to find it .. solved a major problem for our dev team, thank you

If I was conversant in GO I would submit a pull request, but sadly I am not, so I have to ask with cap in hand

Whilst the created domains are in `\etc\hosts` and verbose mode lists a lot of detail it would be super nice to have them output based on a command line switch in a nice readable tabular format, for quick reference by devs

Just thought we would throw it out there, thanks again

**Comment by cjimti** [comment]
@MarkCupitt I'm glad you find it useful! All the domains follow Kubernetes' internal DNS structure so you should also know the name of the service based on that. 

```
<service>
<service>.<namespace>
<service>.<namespace>.svc
<service>.<namespace>.svc.cluster.local
<service>.<namespace>.svc.<context>
```
