### ISSUE TITLE
WARN[18:55:59] WARNING: No Pod selector for service xxx.yyy, skipping

### ISSUE THREAD

**Issue by tianmingxing** [txn2/kubefwd#261]
Can the service resources that proxy external IPs not function properly? Have you considered supporting this scenario?
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/5615719/230249344-d363a727-6c1d-4195-8b9f-a610971a964a.png">

**Comment by cjimti** [comment]
It can only port forward to a Pod; this is a limitation of the Kubernetes API.
