### ISSUE TITLE
kubefwd should respect my current namespace

### ISSUE THREAD

**Issue by cruschke** [txn2/kubefwd#27]
With using [kubens](https://github.com/ahmetb/kubectx) (`kubens the-project`) you easily get used to set your current namespace once and no longer append `-n <yournamespace>` to each and every `kubectl` command.

It would be helpful if `kubefwd` would appreciate my current namespace too, so instead of `kubefwd` defaulting to `default` namespace when being invoked without `-n` it should default to my current namespace (`the-project`).

**Comment by cjimti** [comment]
@cruschke kubefwd 1.4.10 will now use the namespace defined in the context as the default if none are specified.

**Comment by cruschke** [comment]
cool thanks!
