### ISSUE TITLE
Disconnect after sending few request

### ISSUE THREAD

**Issue by deepejai** [txn2/kubefwd#29]
I am connecting to my openshift cluster using below command

```
sudo kubefwd services -n <nameSpace>
```

After sending few requests, I am getting the error  **lost connection to pod**.

![image](https://user-images.githubusercontent.com/6914837/49148842-7f9f6d80-f32e-11e8-839e-00bc46b7aa70.png)

**Comment by cjimti** [comment]
Did you check the pod? is it in a crash loop? 

Also, have you tried to `kubectl port-forward` to a similar pod and if so is that stable?
