### ISSUE TITLE
Reinitialise on SIGHUP

### ISSUE THREAD

**Issue by azuenko** [txn2/kubefwd#31]
It would be great if I can send a SIGHUP to let kubefwd restart its main loop and reinitialise itself. Right now I manually have to go to the terminal window, Ctrl-C it and rerun the command. With a proper handling of the signal it'd be possible to do a single-line deployment, e.g. `helm upgrade && sudo pkill -HUP kubefwd`. Currently on SIGHUP kubefwd just quits. It could partially solve the problem in #21

**Comment by azuenko** [comment]
#21

**Comment by cjimti** [comment]
I will look at supporting this. However I think retry is still needed even in this case since the Pods may not be up that quickly.

**Comment by cjimti** [comment]
#95 should remove the need for sending a SIGHUP. `kubefwd` 1.11.0 watches the Pod backing a Service and reconnects when new a Pod comes online.
