### ISSUE TITLE
kubeconfig file with user token

### ISSUE THREAD

**Issue by bergur88** [txn2/kubefwd#32]
Is it possible to support authentication against kubernetes via user tokens but not only with certificates?
https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

**Comment by cjimti** [comment]
This is supported and how I access some of the clusters I work on. What error are you getting? Can you provide steps to reproduce? Thanks

**Comment by cjimti** [comment]
Please add a comment if you continue to have this issue.

**Comment by bergur88** [comment]
The error i'm getting is: 
```
2018/12/10 10:03:27 ERROR: error upgrading connection: unable to upgrade connection: <!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta id="viewport" name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/assets/images/logos/favicon.ico">
    <title>Loading&hellip;</title>
    <!-- 1.6.37 -->
    <meta name="description" content="">
    <base href="/" />
    <link id = "vendor" rel="stylesheet" href="/assets/vendor.css">
    <link id="theme" rel="stylesheet">

  </head>
  <body>

    <script src="/assets/vendor-77489dadbb0709acf44882f0dde4b110.js"></script>
    <script src="/assets/ui-173435239849ea7eb73d8f2e17732e45.js"></script>
    <div id="ember-basic-dropdown-wormhole"></div>
  </body>
</html>

```

It happens when calling the dialer: 
https://github.com/txn2/kubefwd/blob/9737a005072eb81429158f5b8a9fc429f7feb5a0/pkg/portforward/portforward.go#L150

I have narrowed it down to upgrader.NewConnection in the Negotiate phase of spdy.go.
https://github.com/kubernetes/kubernetes/blob/a69b565c3e92ddedd8676bc4fbb6c4c9d918dec8/staging/src/k8s.io/client-go/transport/spdy/spdy.go#L89
The Upgrader is created by RoundTripperFor in spdy.go but in my case i have not TLSConfig as i'm using tokens for authentication.
https://github.com/kubernetes/kubernetes/blob/a69b565c3e92ddedd8676bc4fbb6c4c9d918dec8/staging/src/k8s.io/client-go/transport/spdy/spdy.go#L37

do you know what might be causing this issue for me ?
