### ISSUE TITLE
kubefwd communication behind a proxy

### ISSUE THREAD

**Issue by bugsbunnyshah** [txn2/kubefwd#33]
Hello,

I am trying to setup local port forwarding to a Kubernetes Cluster. I am behind a proxy. Is there a way to allow communication over a proxy. Here are the log details;

--------
kforward
2018/12/24 15:39:24  _          _           __             _
2018/12/24 15:39:24 | | ___   _| |__   ___ / _|_      ____| |
2018/12/24 15:39:24 | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
2018/12/24 15:39:24 |   <| |_| | |_) |  __/  _|\ V  V / (_| |
2018/12/24 15:39:24 |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
2018/12/24 15:39:24 
2018/12/24 15:39:24 Version 1.4.10
2018/12/24 15:39:24 https://github.com/txn2/kubefwd
2018/12/24 15:39:24 
2018/12/24 15:39:24 Press [Ctrl-C] to stop forwarding.
2018/12/24 15:39:24 'cat /etc/hosts' to see all host entries.
2018/12/24 15:39:24 Loaded hosts file /etc/hosts
2018/12/24 15:39:24 Hostfile management: Original hosts backup already exists at /etc/hosts.original
2018/12/24 15:39:24 Error forwarding service: Get https://gav-cu-ine-dev-aks-91bc5af0.hcp.centralus.azmk8s.io:443/api/v1/namespaces/default/services: dial tcp: lookup gav-cu-ine-dev-aks-91bc5af0.hcp.centralus.azmk8s.io on 10.220.220.220:53: no such host
2018/12/24 15:39:24 Done...
------

Thanks
Sohil
Senior Staff Software Engineer, GE Aviation

**Comment by ulrichSchreiner** [comment]
hi,

i have the same problem. my API-server is only available through a bastion-host. to connect to it, i have a KUBECONFIG which only works if i go through the bastion. so i do:
~~~
ssh -D 8123 bastion.my.host 
~~~
now i have a local SOCKS proxy which i export with
~~~
export https_proxy=socks5://localhost:8123
~~~
and voila, i can use `kubectl` commands as `kubectl` is using the proxy setting.

now i start `kubefwd`:
~~~
sudo https_proxy=socks5://localhost:8123 kubefwd svc -c my-kube-config 
~~~
and now i get errors:
~~~
ERROR: error upgrading connection: error sending request: Post https://<my-ip>:6443/api/v1/namespaces/default/pods/nsqd-0/portforward?timeout=32s: EOF
~~~
it looks like `kubefwd` is using the proxy setting to query the information but not using the proxy when creating the socket connection?
