### ISSUE TITLE
Removes localhost entry and error "Something is already running on port [PORT]"

### ISSUE THREAD

**Issue by kojuka** [txn2/kubefwd#48]
Since upgrading to 1.7.3 kubefwd removes `127.0.0.1 localhost` from /etc/hosts

Typically my work flow is that I will forward my additional cluster services ie:
`sudo kubefwd svc -l "app in (elasticsearch, rabbitmq, redis, mysql)"`

But then I would run a microservice locally to develop on which would run on `localhost:3000`.

However if it removes `127.0.0.1 localhost` then I will always get this error message
`Something is already running on port 3000.`

If I manually edit /etc/hosts and add `127.0.0.1 localhost` then the error message goes away.

Any thoughts on this?  Any work arounds?

**Comment by kojuka** [comment]
![Screenshot 2019-03-21 11 35 14](https://user-images.githubusercontent.com/154551/54772651-67997580-4bcd-11e9-9527-1ec83f6a088c.png)

**Comment by cjimti** [comment]
@kojuka I have the same development process but don't experience that. It should not be removing the hostname "localhost". 

This bug does not reproduce on my end but I can still look at putting a safety net in there. There should never be a need to remove or add "localhost".

Also, when developing locally, if can you will need to bind to 127.0.0.1 or any non-127.1.27.0/24 address. Some people bind to 0.0.0.0 and if that is the case you run the risk of port collisions, for example, kubefwd may be bound to 127.1.28.10:3000 and if you try to put a listener on 0.0.0.0:3000 you will get an error.

**Comment by kojuka** [comment]
@cjimti thanks for the quick response.

After your response I thought maybe something weird was going on.  So I started investigating more. 
I noticed this line:
 ```
2019/03/21 13:41:12 Hostfile management: Original hosts backup already exists at /Users/ken/hosts.original
```

I deleted `/Users/ken/hosts.original` and started kubefwd again.  

This resolved my issue.  Thanks!

**Comment by cjimti** [comment]
@kojuka I am glad to hear that you are up and running again. 

I think this is still a good opportunity for me to continually look for ways harden the /etc/hosts handling. Thanks!
