### ISSUE TITLE
Original /etc/hosts not restored after an error

### ISSUE THREAD

**Issue by vemv** [txn2/kubefwd#5]
Hi there,

I guess that after an error, the original /etc/hosts should be restored, for cleaning things up. It's the behavior I can observe if hitting Ctrl-C when Kubefwd is up and running in a healthy state.

However I found two cases where this didn't happen:

## 1

There was an unexpected error due to some timeout (can't provide more details sorry - no idea what exactly happened). Kubefwd didn't gracefully handle the issue and was seemingly waiting forever.

I hit Ctrl-C, and /etc/hosts wasn't restored.

## 2

In this other case, Kubectl did catch the issue and gracefully turned itself off. But /etc/hosts wasn't restored.

```
~ $ sudo kubefwd services -n default -n kafka

 _          _           __             _
| | ___   _| |__   ___ / _|_      ____| |
| |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
|   <| |_| | |_) |  __/  _|\ V  V / (_| |
|_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|

Press [Ctrl-C] to stop forwarding.
Loading hosts file /etc/hosts
Backing up your original hosts file /etc/hosts to /etc/hosts.original
Fwd 127.1.27.1:5432 as db-postgresql:5432 to pod db-postgresql-0:postgresql
Fwd 127.1.27.2:5432 as db-postgresql-headless:5432 to pod db-postgresql-0:postgresql
Fwd 127.1.27.3:443 as kubernetes:443 to pod db-postgresql-0:8443
Fwd 127.1.28.1:9092 as wd-kafka.kafka.svc.cluster.local:9092 to pod wd-kafka-0:kafka
Fwd 127.1.28.2:9092 as wd-kafka-headless.kafka.svc.cluster.local:9092 to pod wd-kafka-0:9092
Fwd 127.1.28.3:2181 as wd-kafka-zookeeper.kafka.svc.cluster.local:2181 to pod wd-kafka-zookeeper-0:client
Fwd 127.1.28.4:2181 as wd-kafka-zookeeper-headless.kafka.svc.cluster.local:2181 to pod wd-kafka-zookeeper-0:2181
Fwd 127.1.28.4:3888 as wd-kafka-zookeeper-headless.kafka.svc.cluster.local:3888 to pod wd-kafka-zookeeper-0:3888
Fwd 127.1.28.4:2888 as wd-kafka-zookeeper-headless.kafka.svc.cluster.local:2888 to pod wd-kafka-zookeeper-0:2888
E1105 17:41:08.849920   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.849954   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.849971   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.849985   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.850454   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.850513   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.850541   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.850703   34632 portforward.go:190] lost connection to pod
E1105 17:41:08.850739   34632 portforward.go:190] lost connection to pod

Done..
```

Hope the report is useful!

Victor

**Comment by indrayam** [comment]
Yeah, noticed the same issue when I hit `Ctrl+C` to shutdown `kubefwd`. Had to manually copy the `/etc/hosts.original` to `/etc/hosts` to restore the original `/etc/hosts`. 

I am running version 1.4.3 on MacOS Sierra.

**Comment by cjimti** [comment]
@indrayam I don't ever explicitly restore the original, essentially it there if for some reason kubefwd were to really mess up the /etc/hosts file. However, entries should be removed properly after a `Ctrl-C'. I believe I fixed some of the issues that were preventing them from being completely removed. 

If you have time please let me know if you can reproduce this issue in 1.4.5. For now, I am going to close th issue but will re-open if you still have concerns as it should be much more stable in the current release.

**Comment by Charrette** [comment]
Hi,

Using version 1.4.7, I just faced the same issue when no service actually exist on my namespace. No explicit error is raised in this situation (which would be nice) and the program just stop by itself and the /etc/hosts isn't restored.

Here's the output (I didn't CTRL-C)
```
 _          _           __             _
| | ___   _| |__   ___ / _|_      ____| |
| |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
|   <| |_| | |_) |  __/  _|\ V  V / (_| |
|_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|

Press [Ctrl-C] to stop forwarding.
'cat /etc/hosts' to see all host entries.
Loading hosts file /etc/hosts
Original hosts backup already exists at /etc/hosts.original

Done...
```

**Comment by cjimti** [comment]
@Charrette kubefwd does not restore the "hosts.original", it is just there in case you would like to restore it. There was no error thrown since not finding services to forward is technically not an error. 

Please let me know if it left your /etc/hosts is a poor state, that should not happen and would be a bug.
