### ISSUE TITLE
Support multiple running kubefwd processes

### ISSUE THREAD

**Issue by desaintmartin** [txn2/kubefwd#54]
Hello,
I wondered if you have considered to be able to run several independent running kubefwd processes.
I have a lot of different namespaces / projects in a kube cluster and it would be handy to be able to independently start/stop kubefwd for a few resources.

I've seen that the IpC variable is hardcoded, would you accept a PR where it is changed to be variable (and change the way that /etc/hosts is handled)?

**Comment by cjimti** [comment]
I think on the surface this sounds easy to do and simple letting uses to override the starting IpC would be fairly trivial to implement. However, I believe it would be a lot of effort to coordinate writes to /etc/hosts. 

I think automated re-connects when it fails to communicate with a Pod (issue #21) and restarting on HUP (issue #31) might actually solve a lot of use cases around your issue. 

Maybe can start with allowing the IpC override and marking the flag to do so as experimental.

**Comment by zifeo** [comment]
This would definitely help a lot! Currently the host files seems to be the issue.

**Comment by cjimti** [comment]
Kubefwd supports multiple contexts and multiple namespaces. Release [1.11.0](https://github.com/txn2/kubefwd/releases/tag/1.11.0) re-forwards services if pods cycle, so at this point, there should not really be a need to support multiple processes. However, there should probably be a check to warn a user if they try to run multiple.

**Comment by itsiftzis** [comment]
@cjimti does this mean that I can run something like:

`sudo kubefwd services \
             --context context-1 \
             --context context-2
             --namespace ns1 \
             --namespace ns2 \
             --namespace ns3 \
             --verbose \
             --selector "app in
             (
               app1,
               ...
               appX
             )"`

where apps can be in any of the 2 contexts (context-1, context-2) ?
