### ISSUE TITLE
Possibly warn or error on invalid namespace provided?

### ISSUE THREAD

**Issue by jakereps** [txn2/kubefwd#57]
Recently ran into an issue where I fat-fingered a namespace, in a list of many, so the endpoint didn't exist when the code tried to hit it (which I missed because the number of services being forwarded pushed the logs beyond my terminal window). 

After some digging I found that it appears k8s corev1 clientset doesn't alert the user, or error when non-existent namespaces are provided (with valid reason I assume, as one of the functions is to Create that namespace). Would it be worth adding validation on kubefwd to either warn or error if a user provides a namespace that results in no listed services?

It looks like it could be added by doing a check on the length of the `services.Items` slice.
https://github.com/txn2/kubefwd/blob/master/cmd/kubefwd/services/services.go#L243

I'd gladly throw in a PR for this if need be, but understand, since it was user-error, if it's not worth adding.

**Comment by cjimti** [comment]
A warning sounds good. I don't think it should be more than a warning since I often forward from multiple clusters that do not share common namespaces.
