### ISSUE TITLE
Intermittent timeouts on random services

### ISSUE THREAD

**Issue by VihanAgarwal97** [txn2/kubefwd#59]
I am running `sudo kubefwd svc -n staging` on my local machine to test against my cluster. All my services in `staging` forward correctly. Example:

```bash
2019/05/13 10:32:01 Forwarding: card:9010 to pod card-7bbfdb6cc8-l88pg:9010
2019/05/13 10:32:02 Forwarding: checkout:9001 to pod checkout-56b746867b-4q8bl:80
```
However, after a while I see the following errors - 

```bash
2019/05/13 10:32:34 ERROR: error upgrading connection: error dialing backend: dial tcp <ip-redacted>:10250: i/o timeout
2019/05/13 10:32:34 Stopped forwarding checkout in staging.
```

This happens for different services each time I run the command, even though the pods are `running` and have `not restarted`. I can workaround this by running `kubefwd` again and again until the service I want to test against is stable, but it's not ideal.

**Comment by cjimti** [comment]
I can only reproduce this with a poor internet connection. I did have this problem once when a firewall in front of the clusters was timing out connections. 

Do you get this same problem with `kubectl port-forward`? kubefwd uses the same client libs for the connection.

**Comment by cjimti** [comment]
This may also have to do with timeouts configured on the kubelet. I am closing this issues as it relates to the re-connect proposal in #70.
