### ISSUE TITLE
Support watching a namespace

### ISSUE THREAD

**Issue by ecordell** [txn2/kubefwd#61]
It would be nice if we could use kubefwd to watch a namespace and update as the services in a namespace change. It might be a reasonable default behavior as well.

Right now, the use of os signals to kill the port forwarding makes it a little harder to plumb this through. Ideally the port forwarding is cancellable without killing the whole process.

**Comment by calmkart** [comment]
This is a useful feature and I will try to add this feature.
Not only about change pods in the service, but also change services in the namespace.
I will assess the relevant workload and difficulty and work for it.
probably done in few days.

**Comment by cjimti** [comment]
@calmkart I know a lot of people including myself that would love this. however, this _may_ require a fairly significant change to the architecture. It's probably a good time to include at least a basic set of tests for any big change to the code base. thanks!!

**Comment by calmkart** [comment]
@cjimti 
I will try my best to finish it in my spare time. But I am not quite sure if I can do it because I am not a professional. But I'll try to do it.

**Comment by cjimti** [comment]
@calmkart only do what you can/want to. Your contributions have been great for kubefwd. My personal and work schedule gives me very little free myself. No pressure to work on this at all. I will leave it assigned to you for a few weeks and if you don't have time or other priorities it's ok!

**Comment by cjimti** [comment]
Release [1.11.0](https://github.com/txn2/kubefwd/releases/tag/1.11.0) watches the provided namespaces thanks to @calmkart #95
