### ISSUE TITLE
Does not work with EKS

### ISSUE THREAD

**Issue by Spareo** [txn2/kubefwd#62]
I might have missed something somewhere but this does not seem to work with EKS in AWS. EKS requires a special credentials binary that generates a token and it appears that kubefwd is ignoring that requirement and not triggering it when it tries to connect to the cluster. This is all I see in the ouput

```
2019/05/27 16:37:50  _          _           __             _
2019/05/27 16:37:50 | | ___   _| |__   ___ / _|_      ____| |
2019/05/27 16:37:50 | |/ / | | | '_ \ / _ \ |_\ \ /\ / / _  |
2019/05/27 16:37:50 |   <| |_| | |_) |  __/  _|\ V  V / (_| |
2019/05/27 16:37:50 |_|\_\\__,_|_.__/ \___|_|   \_/\_/ \__,_|
2019/05/27 16:37:50
2019/05/27 16:37:50 Version 1.8.2
2019/05/27 16:37:50 https://github.com/txn2/kubefwd
2019/05/27 16:37:50
2019/05/27 16:37:50 Press [Ctrl-C] to stop forwarding.
2019/05/27 16:37:50 'cat /etc/hosts' to see all host entries.
2019/05/27 16:37:50 Loaded hosts file /etc/hosts
2019/05/27 16:37:50 Hostfile management: Original hosts backup already exists at /Users/dkhenkin/hosts.original
2019/05/27 16:37:50 Error forwarding service: Unauthorized
2019/05/27 16:37:50 Done...
```

**Comment by cjimti** [comment]
I don't EKS but I know others have been able to use kubefwd with it. Maybe they change chime in. However, if you can use kubectl you should be able to use kubefwd.

The kubernetes authentication is abstracted in the client API. Dose kubectl work normally?

**Comment by Spareo** [comment]
Yes Kubectl works normally. If its not the issue that I said then is it possible that when kubewd runs its running in a new context and ignoring the environment variables I have set in the current shell? The aws-iam-authenticator looks in the environment variables to get my AWS token info.

**Comment by cjimti** [comment]
You might try `sudo kubefwd svc -x CONTEXT -n NAMESPACE`

**Comment by Spareo** [comment]
Just tried it, same error. I don't think its even getting far enough to try and connect.

**Comment by okgolove** [comment]
Hello! We use EKS and it works properly.

**Comment by Spareo** [comment]
> Hello! We use EKS and it works properly.

How are you setting your AWS credentials? Are you using environment variables or setting them in the credentials file?

**Comment by okgolove** [comment]
@Spareo I have a separated AWS profile
```
cat ~/.aws/config
[profile cluster]
region = eu-west-1
```

And in ~/.kube/config:

```
- name: eks_cluster-dev
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - cluster-dev
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: cluster
```

**Comment by Spareo** [comment]
@okgolove that did the trick, I was hoping it would pick up the environment variables from the shell like kubectl does but seems like for kubefwd it needs to be in the kube config file.
