### ISSUE TITLE
Handling incoming connections

### ISSUE THREAD

**Issue by gitirabassi** [txn2/kubefwd#63]
Kubefwd is amazing because it enables to work on a single service without having to deploy the whole platform on your laptop. This said, it's really rare to develop the only calls other services and it's never called. How can I handle incoming connection to "my service" that is running locally?

**Comment by cjimti** [comment]
@gitirabassi thanks for the input!

kubefwd is a tool for communicating into the cluster, utilizing services that are already running. I believe Telepresence is probably a better choice for want you want to do. I assume you want to create a service in Kubernetes that points to an endpoint on your local workstation? This probably not something that kubefwd will ever do. kubefwd is really intended to help develop apps with a dependency on services already running in the cluster. Re-directing in-cluster service traffic is really out of scope for this little util. 

On a side note, it's also not a development pattern I fully understand. It seems there are more stable ways to achieve the same result by using external services or even just labeled deployments and alternate selectors.

**Comment by gitirabassi** [comment]
Thanks @cjimti. I thought this too but I just don't have enough experience and knowledge about kubefwd to understand if this was a scenario in roadmap or not. 

Keep up the amazing work

**Comment by cjimti** [comment]
I hope I did not sound dismissive. A few people have asked for that capability and I think I just need to better understand the use case. While kubefwd will not likely go that direction it might be interesting to write a utility just for that purpose. 

If it's just a matter of getting a flow of data from the cluster, maybe an event/message queue would be a good option. I use kubefwd to attach to Kafka in-cluster and test even processing locally.

**Comment by gitirabassi** [comment]
@cjimti no no, you didn't sound dismissive at all. I really enjoy how kubefwd works and its semplicity and I'd hate to complicate it trying to add this feature. I run kafka too, and for that is fine. I'd like to make `kubefwd` the de-facto standard for developers, but without this feature I can't do it.

 I'd like to find a kubernetes emblematic solution. Any ideas?
