### ISSUE TITLE
Non-ready pods are selected for forwarding

### ISSUE THREAD

**Issue by JorritSalverda** [txn2/kubefwd#64]
When I redeploy an application and I stop `kubefwd` to restart as soon as the new pod is ready and the old one is in terminating state, the terminating one is still selected. It would be good to check the readiness of all containers in a pod. Or perhaps use endpoints as the source, because that will only show ready pods.

**Comment by cjimti** [comment]
I have added FieldSelector: status.phase=Running when looking for Pods. I plan on putting out another release later this week. Thanks for the report.

**Comment by cjimti** [comment]
in relase [1.9.1](https://github.com/txn2/kubefwd/releases/tag/v1.9.1)
