### ISSUE TITLE
Use localhost + random ports as an alternative

### ISSUE THREAD

**Issue by morningspace** [txn2/kubefwd#68]
To add local DNS lookup in `hosts` is convenient, kind of the core idea of this great tool, but I wonder if that makes sense to have it support localhost with random ports by specifying an additional command line option, just like the usual way that Docker does to expose container ports using its `-P`.

With that, we don't have to modify `hosts`, create loopback alias, etc., hence do not need `sudo` any more. I'm not going to break the original design, just to give people another option, to make it more widely used.

Does it make sense?

**Comment by cjimti** [comment]
I believe you could accomplish that with a shell script and `kubectl port-forward`. Since you don't need to bind to multiple interfaces or have name resolution `kubefwd` may be overkill IMO.

**Comment by morningspace** [comment]
Aha... I was thinking that even w/o multi-interface binding and name resolution, it might still be reasonable to leverage other features in `kubefwd', e.g. allows to specify namespace, selector, context, kubeconfig, etc. So, an additional argument, say `mode=fixed|random`, could support both.

But maybe you are right... I haven't thought about that on the other side... To use `kubectl` w/ shell script or `kubernetes client-go` may also be feasible... just not sure how much things overkilled...I will explore it. Thanks for your reply!

**Comment by cjimti** [comment]
@morningspace im going to close this. I think a new project forked from `kubefwd` might be a great way to experiment with this use case. Thanks for the input!

**Comment by morningspace** [comment]
Sure... @cjimti thanks for your time on this!
