### ISSUE TITLE
fails when running on a system with inetutils installed

### ISSUE THREAD

**Issue by jwtodd** [txn2/kubefwd#77]
os: osx mojave
brew: inetutils installed

> $ sudo kubefwd svc -n default 
> ...
> Cannot ifconfig lo0 alias 127.1.27.1 up

workaround: `brew uninstall inetutils`

**Comment by cjimti** [comment]
@jwtodd, unfortunately, brew's inetutils version of ifconfig has different arguments. `kubefwd` would need to detect the version. Another workaround is to keep the rest of inetutils and unlink ifconfig (unless you really don't want to use the BSD version preinstalled on your mac.)
