### ISSUE TITLE
kubefwd does not write all services on hosts file

### ISSUE THREAD

**Issue by michalis-vitos** [txn2/kubefwd#79]
This is a great tool and thank you for your effort! 

I am currently using version **1.9.1** and I face the following issue: 

When I port forward to a specific namespace, all services show up on the hosts file apart from one.

Here are the logs of **kubefwd** and as you can see there are 6 services and all of them are assigned a loopback IP address:
```
INFO[10:31:12] Version 1.9.1
INFO[10:31:12] https://github.com/txn2/kubefwd
INFO[10:31:12]
INFO[10:31:12] Press [Ctrl-C] to stop forwarding.
INFO[10:31:12] 'cat /etc/hosts' to see all host entries.
INFO[10:31:12] Loaded hosts file /etc/hosts
INFO[10:31:12] Hostfile management: Backing up your original hosts file /etc/hosts to /Users/michalis/hosts.original
INFO[10:31:13] Resolving:  api-1api-1 to 127.1.27.1
INFO[10:31:13] Forwarding: api-1:80 to pod api-1-5f79b5b84c-9wlp4:8080
INFO[10:31:13] Resolving:  api-2api-2 to 127.1.27.2
INFO[10:31:13] Forwarding: api-2:80 to pod api-2-68d5bb5d87-trkfw:8080
INFO[10:31:13] Resolving:  api-3api-3 to 127.1.27.3
INFO[10:31:13] Forwarding: api-3:80 to pod api-3-85695d96f-lqrnq:8080
INFO[10:31:13] Resolving:  api-4api-4 to 127.1.27.4
INFO[10:31:13] Forwarding: api-4:80 to pod api-4-558469fc85-95z77:8080
INFO[10:31:13] Resolving:  api-5api-5 to 127.1.27.5
INFO[10:31:13] Forwarding: api-5:80 to pod api-5-859675b7c4-fb2fk:8080
INFO[10:31:13] Resolving:  api-6api-6 to 127.1.27.6
INFO[10:31:13] Forwarding: api-6:80 to pod api-6-98cc46646-wcndz:8080
INFO[10:31:13] Saving hosts file
```

Then when I check my `/etc/hosts` file, there are only 5 records, instead of 6:
```
127.1.27.1       api-1 api-1.uk.svc.cluster.local api-1.uk
127.1.27.2       api-2 api-2.uk.svc.cluster.local api-2.uk
127.1.27.3       api-3 api-3.uk.svc.cluster.local api-3.uk
127.1.27.4       api-4 api-4.uk.svc.cluster.local api-4.uk
127.1.27.5       api-5 api-5.uk.svc.cluster.local api-5.uk
```

The interesting thing is that if use the IP address `127.1.27.6`, I can access the missing service. The issue is that it just does not appear on the hosts file. I have noticed that it is always `api-6` missing from the hosts file.

On an unrelated note, I have noticed that a few times, when I shutdown **kubefwd** it leaves behind one record on the hosts file.

**Comment by cjimti** [comment]
Thanks for the report I can take a look at it this weekend

**Comment by cjimti** [comment]
@michalis-vitos I am not able to reproduce this. Can you provide more details? Are you able to port forward api-6 with kubectl?

**Comment by michalis-vitos** [comment]
Hi @cjimti, thanks for checking this out.

Yes, I am able to port forward to that service with kubectl. Even with kubefwd, if I use the allocated loopback IP address e.g. `127.1.27.6`, I can access the missing service. The issue is that it just does not appear on the hosts file. For some weird issue it is always api-6 missing from the hosts file.

**Comment by cjimti** [comment]
@michalis-vitos this is a race condition as a consequence of https://github.com/txn2/kubefwd/pull/76

I will push a quick fix that saves again after a two-second delay. I hope to revisit this in the future and add a more stable solution.

**Comment by michalis-vitos** [comment]
Thanks @cjimti, the two seconds delay seems to solve the issue, at least on my case!
