### ISSUE TITLE
Merging kube configs with KUBECONFIG variable.

### ISSUE THREAD

**Issue by stefanjacobs123** [txn2/kubefwd#81]
kubefwd doesn't respect merging configuration files with the KUBECONFIG env variable. 

For instance doing `KUBECONFIG=config:config2` will merge configs `config` and `config2` when doing a `kubectl config view`. 

By default, kubefwd looks at path `~/.kube/config` for the configuration file. However, with the -E flag (to choose a custom configuration file) it uses the path specified in KUBECONFIG. kubefwd, unlike kubectl, however doesn't support a list of configuration files in the KUBECONFIG env.

Shouldn't kubefwd rather use the context & config supplied by `kubectl config view`?

**Comment by calmkart** [comment]
/assign
maybe i can fix this problem, by change the custom configLoader(GetConfig) to k8s configLoader(ToRawKubeConfigLoader)

**Comment by calmkart** [comment]
fixed in #86

**Comment by cjimti** [comment]
Available in release 1.9.4+
