### ISSUE TITLE
fork/exec Too many open files

### ISSUE THREAD

**Issue by okgolove** [txn2/kubefwd#83]
Hi!

I'm using MacOS Catalina.
There are more than 80 services in a namespace I'd like to forward.

I get an error: https://github.com/txn2/kubefwd/blob/5bd54d8349fe2b76115252ce7ac7855c47f1acfb/pkg/fwdnet/fwdnet.go#L61-L62

If you print **err**, you get the error:
```
fork/exec Too many open files
```

The problem is ulimit:

```
launchctl limit maxfiles
        maxfiles    256            unlimited
```

If you rise the limit kubefwd works properly.

Thanks @defval for researching.

1) It would be great to get additional information in case of error.
2) Should kubefwd work with ulimit? May be the problem should be described in the README file?

Thank you!

**Comment by cjimti** [comment]
@okgolove in opening a port I assume counts as an open filehandle. 

I could be wrong. I am not yet on Catalina, what was your solution.
Good idea to print the actual error there.

**Comment by okgolove** [comment]
@cjimti you're absolutely right, every port == file.
Catalina is not the source of the error. The error is reproducible using any Linux/UNIX OS.
