### ISSUE TITLE
"nodes is forbidden" error and EKS issues

### ISSUE THREAD

**Issue by Laptopmini** [txn2/kubefwd#84]
I work with a cluster that is overly locked down for security reasons and it seems that its having issues with the actions performed by this utility when adding said cluster.

```
nodes is forbidden: User "arn:aws:iam::557470950***:user/some@workemail.com" cannot list resource "nodes" in API group "" at the cluster scope
```
Note: `some@workemail.com` is a dummy value I've replaced in this paste.

![Screen Shot 2019-10-24 at 12 17 09 PM](https://user-images.githubusercontent.com/7481777/67518411-a0b13100-f659-11e9-9b9b-8b6af0a34a32.png)

I'll note also that I ran into this while attempting to add a cluster which uses EKS. I have found the following about it, but I'm unable to try it out:
https://github.com/txn2/kubefwd/issues/62#issuecomment-496630133

If I ignore the error mentioned, add the cluster anyway and try to connect to it, I am met with
```
Pod "svc/iotconsole-backend" forbidden.
```
which is usually the message I get in the command line if my AWS token is expired or non-existent. This is however not the case, even if I freshly generate a new one right before trying.
Shouldn't it still work even if the app failed to execute its commands to seek out existing nodes? Wouldn't the two be unrelated?

**Comment by cjimti** [comment]
@Laptopmini what command are you using to run kubefwd? Also, I am not familiar with that dialog box.

**Comment by cjimti** [comment]
I am not familiar with any of the output you have provided. This issue may be referring to another project. Closing unless we can determine how this relates to kubefwd. Thanks
