### ISSUE TITLE
Add the ability to forward services from different namespaces

### ISSUE THREAD

**Issue by kevinjqiu** [txn2/kubefwd#98]
Sometimes we need to interact with services in different namespaces for local development.  It'd be nice if `kubefwd` supports the ability to forward services from different namespaces other than the current one.

This could potentially make `kubefwd` forward too many services if there isn't a way to selectively forward services from other namespaces.  To remedy that, kubefwd could take a config file that specifies what services should be forwarded.

I wouldn't mind taking stab at implementing this feature if you think it's worthwhile.

Cheers,

**Comment by cjimti** [comment]
Use -n as many times as you like. There is no limit to the number of namespaces you can forward.

**Comment by kevinjqiu** [comment]
ok, got it.  Thanks!
